#!/usr/bin/env python3
"""Season calendar data provider for GUI modules.

This helper queries the REST API (function 99) to obtain the season
calendar, transforms the payload into a GUI-friendly structure, and exposes
season events (completed and upcoming) with associated session information.

The provider follows the GUI "API-only" policy: it never spawns CLI
processes. When the API is unavailable it can fall back to the latest local
JSON export generated by the CLI (manual execution by the developer).
"""

from __future__ import annotations

import json
import logging
import os
import re
from dataclasses import dataclass
from datetime import datetime, timezone, timedelta
from pathlib import Path
from typing import Any, Dict, List, Optional

from core import local_requests as requests
import certifi
from core.api_base_url import resolve_api_base_url
from core.logger import get_logger

__all__ = [
    "SeasonCalendarError",
    "SeasonEvent",
    "SeasonSession",
    "SeasonCalendarProvider",
]


API_ENDPOINT = "/api/v2/analysis/execute"
DEFAULT_BASE_URL = "http://localhost:8000"
CONFIG_PATH = Path("config/api_config.json")
JSON_DIR = Path(os.getenv("F1_ANALYSIS_JSON_DIR", "json"))

# 🔄 Calendar 刷新策略：智能加速機制
CALENDAR_REFRESH_HOURS_NORMAL = 168  # 7 天 (正常模式：賽程固定時期)
CALENDAR_REFRESH_HOURS_RACE_APPROACHING = 12  # 12 小時 (臨近模式：賽前 2 天)
RACE_APPROACHING_THRESHOLD_DAYS = 2  # 賽前 2 天啟動加速刷新

SESSION_NAME_MAPPING = (
    ("practice 1", "FP1"),
    ("free practice 1", "FP1"),
    ("practice 2", "FP2"),
    ("free practice 2", "FP2"),
    ("practice 3", "FP3"),
    ("free practice 3", "FP3"),
    ("practice 4", "FP4"),
    ("sprint shootout", "SQ"),
    ("sprint qualifying", "SQ"),
    ("sprint", "S"),  # Sprint race
    ("qualifying", "Q"),
    ("race", "R"),
)

EVENT_NAME_MAP = {
    "australian": "Australia",
    "bahrain": "Bahrain",
    "saudi arabian": "Saudi Arabia",
    "saudi arabia": "Saudi Arabia",
    "chinese": "China",
    "japanese": "Japan",
    "miami": "Miami",
    "emilia romagna": "Emilia Romagna",
    "monaco": "Monaco",
    "spanish": "Spain",
    "canadian": "Canada",
    "austrian": "Austria",
    "styrian": "Austria",
    "british": "Great Britain",
    "belgian": "Belgium",
    "hungarian": "Hungary",
    "dutch": "Netherlands",
    "italian": "Italy",
    "tuscan": "Tuscan",
    "russian": "Russia",
    "eifel": "Eifel",
    "portuguese": "Portugal",
    "turkish": "Turkey",
    "azerbaijan": "Azerbaijan",
    "singapore": "Singapore",
    "qatar": "Qatar",
    "abu dhabi": "Abu Dhabi",
    "las vegas": "Las Vegas",
    "mexico city": "Mexico",
    "mexican": "Mexico",
    "sao paulo": "Brazil",
    "são paulo": "Brazil",
    "brazilian": "Brazil",
    "united states": "United States",
    "austin": "United States",
    "doha": "Qatar",
    "imola": "Emilia Romagna",
    "silverstone": "Great Britain",
    "spielberg": "Austria",
    "sakhir": "Sakhir",
}

COUNTRY_NAME_MAP = {
    "united kingdom": "Great Britain",
    "united states": "United States",
    "usa": "United States",
    "united arab emirates": "Abu Dhabi",
    "people's republic of china": "China",
    "people\u2019s republic of china": "China",
    "korea": "Korea",
    "south korea": "Korea",
    "uae": "Abu Dhabi",
    "sao tome and principe": "São Tomé",  # defensive
}


logger = get_logger(__name__)


class SeasonCalendarError(RuntimeError):
    """Raised when the provider cannot obtain valid calendar data."""


@dataclass(slots=True)
class SeasonSession:
    code: str
    name: str
    local_time: Optional[datetime]
    utc_time: Optional[datetime]


@dataclass(slots=True)
class SeasonEvent:
    round: int
    display_label: str
    race_key: str
    race_date: str
    is_completed: bool
    sessions: List[SeasonSession]
    raw_payload: Dict[str, Any]


class SeasonCalendarProvider:
    """Provide season calendar information for GUI consumers."""

    def __init__(self, *, base_url: Optional[str] = None, timeout: float = 20.0) -> None:
        self._timeout = timeout
        self._base_url = (base_url or self._determine_base_url()).rstrip("/")
        self._cache: Dict[int, List[SeasonEvent]] = {}

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------
    def get_completed_events(self, year: int) -> List[SeasonEvent]:
        """Return season events for the given year.

        The result is cached for the lifetime of the provider instance.
        
        ✨ 智能加速刷新邏輯：
        - 正常模式：7 天刷新一次（賽程固定時期）
        - 臨近模式：賽前 2 天開始，每 12 小時刷新（捕捉賽事完成狀態）
        - 優先檢查本地 JSON 的新鮮度
        - 如果新鮮，直接使用本地 JSON
        - 如果過期或不存在，嘗試通過 API 刷新
        - API 失敗則降級使用舊的 JSON（總比沒有好）
        """

        if year in self._cache:
            return self._cache[year]

        # 🔍 Step 1: 檢查本地 JSON 的新鮮度
        local_json_path, local_json_age_hours = self._get_latest_json_info(year)
        
        # 🏁 Step 2: 判斷是否有賽事臨近（決定刷新頻率）
        refresh_interval_hours = self._determine_refresh_interval(local_json_path, year)
        is_local_fresh = local_json_age_hours is not None and local_json_age_hours < refresh_interval_hours
        
        if is_local_fresh:
            logger.debug(
                "[SEASON] 本地 JSON 仍新鮮（%.1f 小時前，閾值: %s 小時），直接使用",
                local_json_age_hours,
                refresh_interval_hours,
            )
            payload = self._load_latest_json(year)
        else:
            # 🌐 Step 3: 本地 JSON 過期或不存在，嘗試 API 刷新
            if local_json_age_hours is None:
                logger.info("[SEASON] 未找到本地 JSON，嘗試通過 API 獲取")
            else:
                refresh_mode = "加速模式" if refresh_interval_hours == CALENDAR_REFRESH_HOURS_RACE_APPROACHING else "正常模式"
                logger.info(
                    "[SEASON] 本地 JSON 已過期（%.1f 小時前，%s），嘗試通過 API 刷新",
                    local_json_age_hours,
                    refresh_mode,
                )
            
            payload = self._fetch_from_api(year)
            
            # 📁 Step 4: API 失敗，降級使用舊的 JSON
            if payload is None:
                logger.warning("[SEASON] API 不可用，降級使用本地 JSON（即使過期）")
                payload = self._load_latest_json(year)

        if payload is None:
            raise SeasonCalendarError(f"無法取得 {year} 年的賽季日曆資料 (API 與本地 JSON 皆不可用)")

        events = self._transform_payload(payload, year=year)
        self._cache[year] = events
        return events

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------
    def _determine_refresh_interval(self, json_path: Optional[Path], year: int) -> float:
        """
        判斷刷新間隔：根據是否有賽事臨近決定刷新頻率
        
        策略：
        - 正常模式：168 小時（7 天）- 賽程穩定時期
        - 加速模式：12 小時 - 賽前 2 天內，頻繁檢查賽事完成狀態
        
        Returns:
            刷新間隔（小時）
        """
        # 如果沒有本地 JSON，使用正常模式
        if json_path is None:
            return CALENDAR_REFRESH_HOURS_NORMAL
        
        try:
            # 讀取 JSON 並找到即將到來的賽事
            payload = json.loads(json_path.read_text(encoding="utf-8"))
            events = self._transform_payload(payload, year=year)
            
            # 找到最近的未完賽事件
            now = datetime.now(timezone.utc)
            upcoming_events = [e for e in events if not e.is_completed]
            
            if not upcoming_events:
                # 沒有未完賽事件，使用正常模式
                return CALENDAR_REFRESH_HOURS_NORMAL
            
            # 檢查最近的賽事是否在臨近閾值內
            for event in upcoming_events[:3]:  # 只檢查最近 3 場賽事
                race_date_str = event.race_date
                if race_date_str:
                    try:
                        # 解析賽事日期（格式: "2025-10-19"）
                        race_date = datetime.strptime(race_date_str, "%Y-%m-%d").replace(tzinfo=timezone.utc)
                        days_until_race = (race_date - now).days
                        
                        # 🚨 賽前 2 天內或賽後 1 天內，啟用加速模式
                        if -1 <= days_until_race <= RACE_APPROACHING_THRESHOLD_DAYS:
                            logger.info(
                                "[SEASON] 賽事臨近：%s 在 %s 天%s，啟用加速刷新模式（12 小時）",
                                event.race_key,
                                days_until_race,
                                "後" if days_until_race >= 0 else "前",
                            )
                            return CALENDAR_REFRESH_HOURS_RACE_APPROACHING
                    except ValueError:
                        continue
            
            # 沒有臨近賽事，使用正常模式
            return CALENDAR_REFRESH_HOURS_NORMAL
            
        except Exception as e:
            logger.warning("[SEASON] 判斷刷新間隔時出錯: %s，降級使用正常模式", e)
            return CALENDAR_REFRESH_HOURS_NORMAL
    
    def _get_latest_json_info(self, year: int) -> tuple[Optional[Path], Optional[float]]:
        """
        獲取最新的 season calendar JSON 檔案資訊
        
        Returns:
            (檔案路徑, 檔案年齡小時數) 如果找到
            (None, None) 如果找不到
        """
        if not JSON_DIR.exists():
            return (None, None)
        
        all_candidates = sorted(
            JSON_DIR.glob("season_calendar_*.json"),
            key=lambda path: path.stat().st_mtime,
            reverse=True,
        )
        
        for candidate in all_candidates:
            try:
                payload = json.loads(candidate.read_text(encoding="utf-8"))
                
                # 檢查是否包含指定年份的數據
                if self._payload_contains_year(payload, year):
                    # 計算檔案年齡
                    file_mtime = datetime.fromtimestamp(candidate.stat().st_mtime, tz=timezone.utc)
                    now = datetime.now(timezone.utc)
                    age_hours = (now - file_mtime).total_seconds() / 3600
                    
                    return (candidate, age_hours)
                    
            except Exception as e:
                logger.warning("[SEASON] 讀取 %s 失敗: %s", candidate.name, e)
                continue
        
        return (None, None)
    
    def _determine_base_url(self) -> str:
        return resolve_api_base_url(
            config_path=CONFIG_PATH,
            event_logger=lambda message: logger.info("[SEASON] %s", message),
        )

    def _fetch_from_api(self, year: int) -> Optional[Dict[str, Any]]:
        try:
            response = requests.post(
                f"{self._base_url}{API_ENDPOINT}",
                params={"function_id": 99, "year": int(year)},
                headers={"Accept": "application/json"},
                timeout=self._timeout,
                verify=certifi.where(),  # ✅ 明確指定 SSL 證書路徑（EXE 必須）
            )
            response.raise_for_status()
            payload = response.json()
            if not isinstance(payload, dict):
                raise ValueError("API response is not a JSON object")
            if not payload.get("success", False):
                raise ValueError(payload.get("message", "API returned success=False"))
            return payload
        except Exception as exc:
            logger.error("[SEASON] API 請求失敗: %s", exc)
            return None

    def _load_latest_json(self, year: int) -> Optional[Dict[str, Any]]:
        """載入最新的季節日曆 JSON，支援單年和多年格式"""
        if not JSON_DIR.exists():
            return None
        
        # 搜尋所有 season_calendar JSON 檔案
        all_candidates = sorted(
            JSON_DIR.glob("season_calendar_*.json"),
            key=lambda path: path.stat().st_mtime,
            reverse=True,
        )
        
        for candidate in all_candidates:
            try:
                payload = json.loads(candidate.read_text(encoding="utf-8"))
                
                # 檢查是否包含指定年份的數據
                if self._payload_contains_year(payload, year):
                    logger.debug("[SEASON] 從本地 JSON 載入: %s (年份: %s)", candidate.name, year)
                    return payload
                    
            except Exception as e:
                logger.warning("[SEASON] 讀取 %s 失敗: %s", candidate.name, e)
                continue

        logger.warning("[SEASON] 未找到包含 %s 年的本地 JSON 檔案", year)
        return None
    
    def _payload_contains_year(self, payload: Dict[str, Any], year: int) -> bool:
        """檢查 payload 是否包含指定年份的數據"""
        if not isinstance(payload, dict):
            return False
        
        data = payload.get("data")
        if not data:
            return False
        
        # 多年嵌套格式: {"data": {"2020": {...}, "2025": {...}}}
        if isinstance(data, dict) and str(year) in data:
            return True
        
        # 單年格式: {"data": [{...}, {...}]}
        if isinstance(data, list):
            # 檢查 metadata 中的年份
            metadata = payload.get("metadata", {})
            if metadata.get("year") == year:
                return True
        
        return False

    def _transform_payload(self, payload: Dict[str, Any], year: Optional[int] = None) -> List[SeasonEvent]:
        """轉換 payload 為 SeasonEvent 列表，支援單年和多年格式"""
        events: List[SeasonEvent] = []
        
        if logger.isEnabledFor(logging.DEBUG):
            logger.debug("[DEBUG] _transform_payload called with year=%s", year)
            logger.debug("[DEBUG] payload top keys: %s", list(payload.keys()))
        
        # 先解開可能的 API 包裝層
        # API 回應格式: {"data": {"data": {"2025": {...}}}}
        # 本地 JSON 格式: {"data": {"2025": {...}}}
        data_container = payload.get("data")
        if logger.isEnabledFor(logging.DEBUG):
            logger.debug("[DEBUG] data_container type: %s", type(data_container))
            if isinstance(data_container, dict):
                logger.debug("[DEBUG] data_container keys: %s", list(data_container.keys())[:10])  # 只顯示前10個
        
        # 檢查是否有雙層嵌套（API 格式）
        if isinstance(data_container, dict) and "data" in data_container:
            # 如果內層還有 "data" key，且是字典（包含年份 keys），則解開一層
            inner_data = data_container.get("data")
            # 修正：檢查 key 是否為年份格式（4位數字字符串）
            if isinstance(inner_data, dict) and any(str(k).isdigit() and len(str(k)) == 4 for k in inner_data.keys()):
                data_container = inner_data
        
        # 處理多年嵌套格式
        if isinstance(data_container, dict) and year is not None:
            # 多年格式: {"data": {"2020": {...}, "2025": {...}}}
            year_str = str(year)
            if logger.isEnabledFor(logging.DEBUG):
                logger.debug("[DEBUG] 尋找年份 %s", year_str)
                logger.debug("[DEBUG] data_container keys: %s", list(data_container.keys()))
                logger.debug("[DEBUG] %s in keys: %s", year_str, year_str in data_container)
            if year_str in data_container:
                year_data = data_container[year_str]
                # 遞迴處理單年數據
                if isinstance(year_data, dict):
                    raw_events = self._extract_event_records(year_data.get("data"))
                else:
                    raw_events = self._extract_event_records(year_data)
            else:
                logger.warning("[SEASON] payload 中未找到 %s 年的數據", year)
                logger.info("[SEASON] 可用的年份: %s", list(data_container.keys()))
                return events
        else:
            # 單年格式: {"data": [{...}, {...}]}
            raw_events = self._extract_event_records(data_container)
        
        if not raw_events:
            return events

        now = datetime.now(timezone.utc)
        for item in raw_events:
            is_completed = bool(item.get("is_completed"))
            race_key = self._canonical_race_key(item)
            race_date_iso = item.get("race_date_local") or item.get("race_date_utc")
            race_date = self._format_date(race_date_iso)
            sessions = self._extract_sessions(item.get("session_dates", {}), reference=now)
            display_label = f"{race_key} ({race_date})" if race_date else race_key

            events.append(
                SeasonEvent(
                    round=int(item.get("round", 0) or 0),
                    display_label=display_label,
                    race_key=race_key,
                    race_date=race_date,
                    is_completed=is_completed,
                    sessions=sessions,
                    raw_payload=item,
                )
            )

        events.sort(key=lambda event: event.round)
        return events

    def _extract_event_records(self, container: Any) -> List[Dict[str, Any]]:
        if isinstance(container, list):
            return [item for item in container if isinstance(item, dict)]
        if isinstance(container, dict):
            for key in ("data", "events", "results", "items"):
                nested = container.get(key)
                records = self._extract_event_records(nested)
                if records:
                    return records
        return []

    def _canonical_race_key(self, event: Dict[str, Any]) -> str:
        name = str(event.get("event_name") or "").strip()
        location = str(event.get("location") or "").strip()
        country = str(event.get("country") or "").strip()

        lower_name = name.lower()
        for pattern, result in EVENT_NAME_MAP.items():
            if pattern in lower_name:
                return result

        lower_location = location.lower()
        for pattern, result in EVENT_NAME_MAP.items():
            if pattern in lower_location:
                return result

        lower_country = country.lower()
        if lower_country in COUNTRY_NAME_MAP:
            return COUNTRY_NAME_MAP[lower_country]

        if country:
            return country
        if name:
            cleaned = re.sub(r"\s*grand prix\s*", "", name, flags=re.IGNORECASE)
            return cleaned or name
        if location:
            return location
        return "Unknown"

    def _extract_sessions(
        self, session_block: Dict[str, Any], *, reference: datetime
    ) -> List[SeasonSession]:
        sessions: List[SeasonSession] = []
        for idx in range(1, 7):
            name_key = f"session{idx}_name"
            local_key = f"session{idx}_local"
            utc_key = f"session{idx}_utc"
            raw_name = session_block.get(name_key)
            if not raw_name:
                continue

            code = self._map_session_code(str(raw_name))
            if code is None:
                continue

            local_dt = self._parse_datetime(session_block.get(local_key))
            utc_dt = self._parse_datetime(session_block.get(utc_key))
            # 僅保留已經發生的會話
            if utc_dt and utc_dt > reference:
                continue

            sessions.append(
                SeasonSession(code=code, name=str(raw_name), local_time=local_dt, utc_time=utc_dt)
            )

        # 去除重複並依時間排序
        unique: Dict[str, SeasonSession] = {}
        for session in sorted(sessions, key=lambda s: (s.utc_time or s.local_time or reference)):
            unique.setdefault(session.code, session)
        ordered_codes = ["FP1", "FP2", "FP3", "FP4", "SQ", "S", "Q", "R"]
        return sorted(unique.values(), key=lambda sess: ordered_codes.index(sess.code) if sess.code in ordered_codes else 99)

    def _map_session_code(self, name: str) -> Optional[str]:
        lower_name = name.lower()
        for pattern, code in SESSION_NAME_MAPPING:
            if pattern in lower_name:
                return code
        return None

    @staticmethod
    def _parse_datetime(value: Any) -> Optional[datetime]:
        if not value:
            return None
        text = str(value)
        if text.endswith("Z"):
            text = text[:-1] + "+00:00"
        try:
            dt = datetime.fromisoformat(text)
            if dt.tzinfo is None:
                return dt.replace(tzinfo=timezone.utc)
            return dt
        except ValueError:
            return None

    @staticmethod
    def _format_date(value: Any) -> str:
        dt = SeasonCalendarProvider._parse_datetime(value)
        if dt is None:
            return ""
        return dt.date().isoformat()
