#!/usr/bin/env python3
"""Season calendar data provider for GUI modules.

This helper queries the REST API (function 99) to obtain the season
calendar, transforms the payload into a GUI-friendly structure, and exposes
season events (completed and upcoming) with associated session information.

The provider follows the GUI "API-only" policy: it never spawns CLI
processes. When the API is unavailable it can fall back to the latest local
JSON export generated by the CLI (manual execution by the developer).
"""

from __future__ import annotations

import json
import os
import re
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

import requests
from core.api_base_url import resolve_api_base_url

__all__ = [
    "SeasonCalendarError",
    "SeasonEvent",
    "SeasonSession",
    "SeasonCalendarProvider",
]


API_ENDPOINT = "/api/v2/analysis/execute"
DEFAULT_BASE_URL = "https://api.f1telemetrystationpro.org"
CONFIG_PATH = Path("config/api_config.json")
JSON_DIR = Path(os.getenv("F1_ANALYSIS_JSON_DIR", "json"))

SESSION_NAME_MAPPING = (
    ("practice 1", "FP1"),
    ("free practice 1", "FP1"),
    ("practice 2", "FP2"),
    ("free practice 2", "FP2"),
    ("practice 3", "FP3"),
    ("free practice 3", "FP3"),
    ("practice 4", "FP4"),
    ("sprint shootout", "SQ"),
    ("sprint qualifying", "SQ"),
    ("qualifying", "Q"),
    ("race", "R"),
)

EVENT_NAME_MAP = {
    "australian": "Australia",
    "bahrain": "Bahrain",
    "saudi arabian": "Saudi Arabia",
    "saudi arabia": "Saudi Arabia",
    "chinese": "China",
    "japanese": "Japan",
    "miami": "Miami",
    "emilia romagna": "Emilia Romagna",
    "monaco": "Monaco",
    "spanish": "Spain",
    "canadian": "Canada",
    "austrian": "Austria",
    "styrian": "Austria",
    "british": "Great Britain",
    "belgian": "Belgium",
    "hungarian": "Hungary",
    "dutch": "Netherlands",
    "italian": "Italy",
    "tuscan": "Tuscan",
    "russian": "Russia",
    "eifel": "Eifel",
    "portuguese": "Portugal",
    "turkish": "Turkey",
    "azerbaijan": "Azerbaijan",
    "singapore": "Singapore",
    "qatar": "Qatar",
    "abu dhabi": "Abu Dhabi",
    "las vegas": "Las Vegas",
    "mexico city": "Mexico",
    "mexican": "Mexico",
    "sao paulo": "Brazil",
    "são paulo": "Brazil",
    "brazilian": "Brazil",
    "united states": "United States",
    "austin": "United States",
    "doha": "Qatar",
    "imola": "Emilia Romagna",
    "silverstone": "Great Britain",
    "spielberg": "Austria",
    "sakhir": "Sakhir",
}

COUNTRY_NAME_MAP = {
    "united kingdom": "Great Britain",
    "united states": "United States",
    "usa": "United States",
    "united arab emirates": "Abu Dhabi",
    "people's republic of china": "China",
    "people\u2019s republic of china": "China",
    "korea": "Korea",
    "south korea": "Korea",
    "uae": "Abu Dhabi",
    "sao tome and principe": "São Tomé",  # defensive
}


class SeasonCalendarError(RuntimeError):
    """Raised when the provider cannot obtain valid calendar data."""


@dataclass(slots=True)
class SeasonSession:
    code: str
    name: str
    local_time: Optional[datetime]
    utc_time: Optional[datetime]


@dataclass(slots=True)
class SeasonEvent:
    round: int
    display_label: str
    race_key: str
    race_date: str
    is_completed: bool
    sessions: List[SeasonSession]
    raw_payload: Dict[str, Any]


class SeasonCalendarProvider:
    """Provide season calendar information for GUI consumers."""

    def __init__(self, *, base_url: Optional[str] = None, timeout: float = 20.0) -> None:
        self._timeout = timeout
        self._base_url = (base_url or self._determine_base_url()).rstrip("/")
        self._cache: Dict[int, List[SeasonEvent]] = {}

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------
    def get_completed_events(self, year: int) -> List[SeasonEvent]:
        """Return season events for the given year.

        The result is cached for the lifetime of the provider instance.
        """

        if year in self._cache:
            return self._cache[year]

        payload = self._fetch_from_api(year)
        if payload is None:
            payload = self._load_latest_json(year)

        if payload is None:
            raise SeasonCalendarError(f"無法取得 {year} 年的賽季日曆資料 (API 與本地 JSON 皆不可用)")

        events = self._transform_payload(payload, year=year)
        self._cache[year] = events
        return events

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------
    def _determine_base_url(self) -> str:
        return resolve_api_base_url(
            config_path=CONFIG_PATH,
            event_logger=lambda message: print(f"[SEASON] {message}"),
        )

    def _fetch_from_api(self, year: int) -> Optional[Dict[str, Any]]:
        try:
            response = requests.post(
                f"{self._base_url}{API_ENDPOINT}",
                params={"function_id": 99, "year": int(year)},
                headers={"Accept": "application/json"},
                timeout=self._timeout,
            )
            response.raise_for_status()
            payload = response.json()
            if not isinstance(payload, dict):
                raise ValueError("API response is not a JSON object")
            if not payload.get("success", False):
                raise ValueError(payload.get("message", "API returned success=False"))
            return payload
        except Exception as exc:
            print(f"[SEASON] API 請求失敗: {exc}")
            return None

    def _load_latest_json(self, year: int) -> Optional[Dict[str, Any]]:
        """載入最新的季節日曆 JSON，支援單年和多年格式"""
        if not JSON_DIR.exists():
            return None
        
        # 搜尋所有 season_calendar JSON 檔案
        all_candidates = sorted(
            JSON_DIR.glob("season_calendar_*.json"),
            key=lambda path: path.stat().st_mtime,
            reverse=True,
        )
        
        for candidate in all_candidates:
            try:
                payload = json.loads(candidate.read_text(encoding="utf-8"))
                
                # 檢查是否包含指定年份的數據
                if self._payload_contains_year(payload, year):
                    print(f"[SEASON] 從本地 JSON 載入: {candidate.name} (年份: {year})")
                    return payload
                    
            except Exception as e:
                print(f"[SEASON] 讀取 {candidate.name} 失敗: {e}")
                continue
        
        print(f"[SEASON] 未找到包含 {year} 年的本地 JSON 檔案")
        return None
    
    def _payload_contains_year(self, payload: Dict[str, Any], year: int) -> bool:
        """檢查 payload 是否包含指定年份的數據"""
        if not isinstance(payload, dict):
            return False
        
        data = payload.get("data")
        if not data:
            return False
        
        # 多年嵌套格式: {"data": {"2020": {...}, "2025": {...}}}
        if isinstance(data, dict) and str(year) in data:
            return True
        
        # 單年格式: {"data": [{...}, {...}]}
        if isinstance(data, list):
            # 檢查 metadata 中的年份
            metadata = payload.get("metadata", {})
            if metadata.get("year") == year:
                return True
        
        return False

    def _transform_payload(self, payload: Dict[str, Any], year: Optional[int] = None) -> List[SeasonEvent]:
        """轉換 payload 為 SeasonEvent 列表，支援單年和多年格式"""
        events: List[SeasonEvent] = []
        
        print(f"[DEBUG] _transform_payload called with year={year}")
        print(f"[DEBUG] payload top keys: {list(payload.keys())}")
        
        # 先解開可能的 API 包裝層
        # API 回應格式: {"data": {"data": {"2025": {...}}}}
        # 本地 JSON 格式: {"data": {"2025": {...}}}
        data_container = payload.get("data")
        print(f"[DEBUG] data_container type: {type(data_container)}")
        if isinstance(data_container, dict):
            print(f"[DEBUG] data_container keys: {list(data_container.keys())[:10]}")  # 只顯示前10個
        
        # 檢查是否有雙層嵌套（API 格式）
        if isinstance(data_container, dict) and "data" in data_container:
            # 如果內層還有 "data" key，且是字典（包含年份 keys），則解開一層
            inner_data = data_container.get("data")
            # 修正：檢查 key 是否為年份格式（4位數字字符串）
            if isinstance(inner_data, dict) and any(str(k).isdigit() and len(str(k)) == 4 for k in inner_data.keys()):
                data_container = inner_data
        
        # 處理多年嵌套格式
        if isinstance(data_container, dict) and year is not None:
            # 多年格式: {"data": {"2020": {...}, "2025": {...}}}
            year_str = str(year)
            print(f"[DEBUG] 尋找年份 {year_str}")
            print(f"[DEBUG] data_container keys: {list(data_container.keys())}")
            print(f"[DEBUG] {year_str} in keys: {year_str in data_container}")
            if year_str in data_container:
                year_data = data_container[year_str]
                # 遞迴處理單年數據
                if isinstance(year_data, dict):
                    raw_events = self._extract_event_records(year_data.get("data"))
                else:
                    raw_events = self._extract_event_records(year_data)
            else:
                print(f"[SEASON] payload 中未找到 {year} 年的數據")
                print(f"[SEASON] 可用的年份: {list(data_container.keys())}")
                return events
        else:
            # 單年格式: {"data": [{...}, {...}]}
            raw_events = self._extract_event_records(data_container)
        
        if not raw_events:
            return events

        now = datetime.now(timezone.utc)
        for item in raw_events:
            is_completed = bool(item.get("is_completed"))
            race_key = self._canonical_race_key(item)
            race_date_iso = item.get("race_date_local") or item.get("race_date_utc")
            race_date = self._format_date(race_date_iso)
            sessions = self._extract_sessions(item.get("session_dates", {}), reference=now)
            display_label = f"{race_key} ({race_date})" if race_date else race_key

            events.append(
                SeasonEvent(
                    round=int(item.get("round", 0) or 0),
                    display_label=display_label,
                    race_key=race_key,
                    race_date=race_date,
                    is_completed=is_completed,
                    sessions=sessions,
                    raw_payload=item,
                )
            )

        events.sort(key=lambda event: event.round)
        return events

    def _extract_event_records(self, container: Any) -> List[Dict[str, Any]]:
        if isinstance(container, list):
            return [item for item in container if isinstance(item, dict)]
        if isinstance(container, dict):
            for key in ("data", "events", "results", "items"):
                nested = container.get(key)
                records = self._extract_event_records(nested)
                if records:
                    return records
        return []

    def _canonical_race_key(self, event: Dict[str, Any]) -> str:
        name = str(event.get("event_name") or "").strip()
        location = str(event.get("location") or "").strip()
        country = str(event.get("country") or "").strip()

        lower_name = name.lower()
        for pattern, result in EVENT_NAME_MAP.items():
            if pattern in lower_name:
                return result

        lower_location = location.lower()
        for pattern, result in EVENT_NAME_MAP.items():
            if pattern in lower_location:
                return result

        lower_country = country.lower()
        if lower_country in COUNTRY_NAME_MAP:
            return COUNTRY_NAME_MAP[lower_country]

        if country:
            return country
        if name:
            cleaned = re.sub(r"\s*grand prix\s*", "", name, flags=re.IGNORECASE)
            return cleaned or name
        if location:
            return location
        return "Unknown"

    def _extract_sessions(
        self, session_block: Dict[str, Any], *, reference: datetime
    ) -> List[SeasonSession]:
        sessions: List[SeasonSession] = []
        for idx in range(1, 7):
            name_key = f"session{idx}_name"
            local_key = f"session{idx}_local"
            utc_key = f"session{idx}_utc"
            raw_name = session_block.get(name_key)
            if not raw_name:
                continue

            code = self._map_session_code(str(raw_name))
            if code is None:
                continue

            local_dt = self._parse_datetime(session_block.get(local_key))
            utc_dt = self._parse_datetime(session_block.get(utc_key))
            # 僅保留已經發生的會話
            if utc_dt and utc_dt > reference:
                continue

            sessions.append(
                SeasonSession(code=code, name=str(raw_name), local_time=local_dt, utc_time=utc_dt)
            )

        # 去除重複並依時間排序
        unique: Dict[str, SeasonSession] = {}
        for session in sorted(sessions, key=lambda s: (s.utc_time or s.local_time or reference)):
            unique.setdefault(session.code, session)
        ordered_codes = ["FP1", "FP2", "FP3", "FP4", "SQ", "Q", "R"]
        return sorted(unique.values(), key=lambda sess: ordered_codes.index(sess.code) if sess.code in ordered_codes else 99)

    def _map_session_code(self, name: str) -> Optional[str]:
        lower_name = name.lower()
        for pattern, code in SESSION_NAME_MAPPING:
            if pattern in lower_name:
                return code
        return None

    @staticmethod
    def _parse_datetime(value: Any) -> Optional[datetime]:
        if not value:
            return None
        text = str(value)
        if text.endswith("Z"):
            text = text[:-1] + "+00:00"
        try:
            dt = datetime.fromisoformat(text)
            if dt.tzinfo is None:
                return dt.replace(tzinfo=timezone.utc)
            return dt
        except ValueError:
            return None

    @staticmethod
    def _format_date(value: Any) -> str:
        dt = SeasonCalendarProvider._parse_datetime(value)
        if dt is None:
            return ""
        return dt.date().isoformat()
