"""Multi-language help catalog for the CLI toolchain."""

from __future__ import annotations

from typing import Iterable, List

from .cli_language import resolve_cli_language

_ZH_TW_HELP_TEXT = (
    "\n"
    "📖 F1分析CLI - 模組化版本使用說明 (v5.4 CLI專用版)\n"
    f"{'=' * 80}\n"
    "這是完全模組化的F1分析系統，僅支援CLI參數化模式。\n"
    "基於FastF1和OpenF1官方API，支援2024-2025年F1賽季的專業級遙測數據分析。\n"
    "✨ 新功能: 增強型賽事選擇界面，顯示賽事日期與完整Grand Prix名稱\n"
    "\n"
    "[FINISH] 賽事選擇增強功能\n"
    f"{'─' * 80}\n"
    "• [CALENDAR] 顯示每場比賽的確切日期\n"
    "• 🏆 顯示完整的Grand Prix正式名稱\n"
    "• [STATS] 更清晰的表格化賽事列表\n"
    "• 🌍 支援2024-2025年完整賽季日程\n"
    "\n"
    "[RAIN]  基礎分析模組 (功能1-10)\n"
    f"{'=' * 80}\n"
    "1.  [RAIN] 增強版降雨強度分析 (Enhanced Rain Intensity Analysis)\n"
    "    功能描述：基於FastF1直接數據，輸出簡化JSON格式的降雨分析\n"
    "    輸入參數：年份、賽事、賽段類型\n"
    "    主要輸出：\n"
    "      [JSON] 結構化輸出：\n"
    "        • temperature_vs_lap (溫度vs圈數)\n"
    "        • rain_vs_lap (降雨vs圈數)\n"
    "        • humidity_vs_lap (濕度vs圈數)\n"
    "        • windspeed_vs_lap (風速vs圈數)\n"
    "        • pressure_vs_lap (氣壓vs圈數)\n"
    "      [CACHE] 緩存整合：支援 pickle 快取機制\n"
    "      [NOTE] 使用最新增強版降雨分析模組 (CLI_modules/cli/analyzer/weather/rain_analyzer.py)\n"
    "\n"
    "2.  [TRACK] 賽道路線分析 (Track Path Analysis)\n"
    "    功能描述：分析車手在賽道上的行駛路線和最佳賽車線\n"
    "    輸入參數：年份、賽事、賽段類型、車手選擇(可選)\n"
    "    主要輸出：\n"
    "      [STATS] Table格式：\n"
    "        • Track_Path_Coordinates (賽道路線座標表)\n"
    "          - Columns: X, Y, Z, Speed, Distance, Sector\n"
    "        • Racing_Line_Analysis (賽車線分析表)\n"
    "          - Columns: CornerNumber, OptimalSpeed, ActualSpeed, LineDifference\n"
    "      [CHART] Figure輸出：\n"
    "        • track_layout_with_paths.png (賽道布局與路線圖)\n"
    "        • racing_line_heatmap.png (賽車線熱力圖)\n"
    "        • speed_zones_visualization.png (速度區域視覺化)\n"
    "\n"
    "3.  [PIT] 車手最快進站時間排行榜 (Driver Fastest Pitstop Ranking)\n"
    "    功能描述：統計各車手最快的進站時間表現\n"
    "    輸入參數：年份、賽事、賽段類型\n"
    "    主要輸出：\n"
    "      [STATS] Table格式：\n"
    "        • Pitstop_Time_Ranking (進站時間排行表)\n"
    "          - Columns: Driver, FastestPitstop, AveragePitstop, PitstopCount\n"
    "\n"
    "4.  [PIT] 車隊進站時間排行榜 (Team Pitstop Ranking)\n"
    "    功能描述：統計各車隊的進站時間表現\n"
    "    輸入參數：年份、賽事、賽段類型\n"
    "    主要輸出：\n"
    "      [STATS] Table格式：\n"
    "        • Team_Pitstop_Ranking (車隊進站排行表)\n"
    "          - Columns: Team, AveragePitstop, BestPitstop, PitstopCount\n"
    "\n"
    "5.  [PIT] 車手進站詳細記錄 (Driver Detailed Pitstop Records)\n"
    "    功能描述：詳細記錄指定車手的進站情況\n"
    "    輸入參數：年份、賽事、賽段類型、車手縮寫\n"
    "    主要輸出：\n"
    "      [STATS] Table格式：\n"
    "        • Pitstop_Details (進站詳細記錄表)\n"
    "          - Columns: LapNumber, PitstopTime, TyreCompound, PositionChange\n"
    "\n"
    "6.  💥 事故統計摘要分析 (Accident Statistics Summary)\n"
    "    功能描述：統計比賽中的事故事件總覽\n"
    "    輸入參數：年份、賽事、賽段類型\n"
    "    主要輸出：\n"
    "      [STATS] Table格式：\n"
    "        • Accident_Summary (事故摘要表)\n"
    "          - Columns: TotalAccidents, DriversInvolved, Locations, SeverityLevels\n"
    "\n"
    "7.  💥 嚴重程度分佈分析 (Severity Distribution Analysis)\n"
    "    功能描述：分析事故嚴重程度的分布情況\n"
    "    輸入參數：年份、賽事、賽段類型\n"
    "    主要輸出：\n"
    "      [STATS] Table格式：\n"
    "        • Severity_Distribution (嚴重程度分布表)\n"
    "          - Columns: SeverityLevel, Count, Percentage, MostCommonLocation\n"
    "\n"
    "8.  💥 所有事件詳細列表分析 (All Incidents Summary)\n"
    "    功能描述：列出所有比賽事件的詳細信息\n"
    "    輸入參數：年份、賽事、賽段類型\n"
    "    主要輸出：\n"
    "      [STATS] Table格式：\n"
    "        • All_Incidents_List (所有事件列表)\n"
    "          - Columns: Time, IncidentType, Drivers, Location, Details\n"
    "\n"
    "9.  💥 特殊事件報告分析 (Special Incident Reports)\n"
    "    功能描述：分析特殊的比賽事件\n"
    "    輸入參數：年份、賽事、賽段類型\n"
    "    主要輸出：\n"
    "      [STATS] Table格式：\n"
    "        • Special_Incidents (特殊事件表)\n"
    "          - Columns: IncidentType, Time, Drivers, Impact, Details\n"
    "\n"
    "10. 💥 關鍵事件摘要分析 (Key Events Summary)\n"
    "    功能描述：總結比賽中的關鍵事件\n"
    "    輸入參數：年份、賽事、賽段類型\n"
    "    主要輸出：\n"
    "      [STATS] Table格式：\n"
    "        • Key_Events_Summary (關鍵事件摘要表)\n"
    "          - Columns: EventType, Time, Description, RaceImpact\n"
    "\n"
    "[F1] 單車手分析模組 (功能11-20)\n"
    f"{'=' * 80}\n"
    "11. [F1] 單一車手綜合分析 (Single Driver Comprehensive Analysis)\n"
    "    ⚠️  狀態：已棄用 (DEPRECATED)\n"
    "    功能描述：指定車手的詳細賽事表現分析\n"
    "    輸入參數：年份、賽事、賽段類型、車手縮寫\n"
    "    主要輸出：\n"
    "      [STATS] Table格式：\n"
    "        • Driver_Performance_Summary (車手表現摘要)\n"
    "          - Columns: LapNumber, LapTime, Position, SectorTimes, Speed\n"
    "\n"
    "12. 📡 單一車手詳細遙測分析 (Single Driver Detailed Telemetry)\n"
    "    功能描述：深度分析單一車手的遙測數據\n"
    "    輸入參數：年份、賽事、賽段類型、車手縮寫、圈數選擇\n"
    "    主要輸出：\n"
    "      [STATS] Table格式：\n"
    "        • Telemetry_Data (遙測數據表)\n"
    "          - Columns: Distance, Speed, Throttle, Brake, Gear, RPM, DRS\n"
    "        • Performance_Metrics (性能指標表)\n"
    "          - Columns: Metric, Value, OptimalValue, Difference, Percentage\n"
    "      [CHART] Figure輸出：\n"
    "        • speed_trace.png (速度軌跡圖)\n"
    "        • throttle_brake_analysis.png (油門煞車分析)\n"
    "        • gear_shift_patterns.png (換檔模式圖)\n"
    "\n"
    "13. [BALANCE] 雙車手比較分析 (Driver Comparison)\n"
    "    功能描述：比較兩位車手的詳細表現\n"
    "    輸入參數：年份、賽事、賽段類型、兩位車手縮寫\n"
    "    主要輸出：\n"
    "      [STATS] Table格式：\n"
    "        • Driver_Comparison_Table (車手對比表)\n"
    "          - Columns: Metric, Driver1_Value, Driver2_Value, Difference, Winner\n"
    "        • Lap_by_Lap_Comparison (逐圈對比表)\n"
    "          - Columns: LapNumber, Driver1_Time, Driver2_Time, TimeDiff, PositionDiff\n"
    "      [CHART] Figure輸出：\n"
    "        • lap_time_comparison.png (圈速對比圖)\n"
    "        • telemetry_overlay.png (遙測數據疊加圖)\n"
    "\n"
    "14. [CHART] 賽事位置變化圖 (Race Position Changes)\n"
    "    ⚠️  狀態：已棄用 (DEPRECATED)\n"
    "    功能描述：顯示賽事中位置變化的圖表\n"
    "    輸入參數：年份、賽事、賽段類型\n"
    "    主要輸出：\n"
    "      [CHART] Figure輸出：\n"
    "        • position_changes_chart.png (位置變化圖)\n"
    "\n"
    "15. [START] 賽事超車統計分析 (Race Overtaking Statistics)\n"
    "    功能描述：統計賽事中的超車事件\n"
    "    輸入參數：年份、賽事、賽段類型\n"
    "    主要輸出：\n"
    "      [STATS] Table格式：\n"
    "        • Overtaking_Statistics (超車統計表)\n"
    "          - Columns: TotalOvertakes, Successful, Failed, KeyMoments\n"
    "\n"
    "16. [FINISH] 單一車手超車分析 (Single Driver Overtaking)\n"
    "    功能描述：分析指定車手的超車和被超車情況\n"
    "    輸入參數：年份、賽事、賽段類型、車手縮寫\n"
    "    主要輸出：\n"
    "      [STATS] Table格式：\n"
    "        • Overtaking_Events (超車事件表)\n"
    "          - Columns: LapNumber, Location, Type, TargetDriver, Success, Method\n"
    "        • Overtaking_Statistics (超車統計表)\n"
    "          - Columns: Total_Overtakes, Successful, Failed, DefensiveActions\n"
    "      [CHART] Figure輸出：\n"
    "        • overtaking_timeline.png (超車時間軸)\n"
    "        • track_overtaking_zones.png (賽道超車區域圖)\n"
    "\n"
    "17. [TARGET] 動態彎道檢測分析 (Dynamic Corner Detection)\n"
    "    ⭐ 狀態：新增功能 (NEW)\n"
    "    功能描述：動態檢測和分析賽道彎道\n"
    "    輸入參數：年份、賽事、賽段類型\n"
    "    主要輸出：\n"
    "      [STATS] Table格式：\n"
    "        • Corner_Detection_Results (彎道檢測結果表)\n"
    "          - Columns: CornerNumber, StartPoint, EndPoint, Radius, Speed\n"
    "\n"
    "18. [TARGET] 彎道詳細分析 (Corner Detailed Analysis)\n"
    "    功能描述：詳細分析指定彎道的表現\n"
    "    輸入參數：年份、賽事、賽段類型、彎道編號\n"
    "    主要輸出：\n"
    "      [STATS] Table格式：\n"
    "        • Corner_Performance (彎道表現表)\n"
    "          - Columns: LapNumber, Entry_Speed, Apex_Speed, Exit_Speed, Time_Through_Corner\n"
    "        • Corner_Statistics (彎道統計表)\n"
    "          - Columns: Best_Speed, Average_Speed, Consistency, Improvement_Rate\n"
    "      [CHART] Figure輸出：\n"
    "        • corner_speed_progression.png (彎道速度進步圖)\n"
    "        • racing_line_corner.png (彎道賽車線分析)\n"
    "\n"
    "19. [TOOL] 單一車手DNF分析 (Single Driver DNF Analysis)\n"
    "    功能描述：分析指定車手的DNF情況\n"
    "    輸入參數：年份、賽事、賽段類型、車手縮寫\n"
    "    主要輸出：\n"
    "      [STATS] Table格式：\n"
    "        • DNF_Analysis (DNF分析表)\n"
    "          - Columns: DNF_Reason, LapNumber, Position_Before_DNF, PreDNF_Performance\n"
    "        • Reliability_Metrics (可靠性指標表)\n"
    "          - Columns: Component, Status, WarningSignals, PredictedFailure\n"
    "      [CHART] Figure輸出：\n"
    "        • performance_before_dnf.png (DNF前表現圖)\n"
    "        • failure_analysis.png (故障分析圖)\n"
    "\n"
    "20. [TARGET] 單一車手全部彎道分析 (Single Driver All Corners)\n"
    "    功能描述：分析指定車手在所有彎道的表現\n"
    "    輸入參數：年份、賽事、賽段類型、車手縮寫\n"
    "    主要輸出：\n"
    "      [STATS] Table格式：\n"
    "        • All_Corners_Performance (全彎道表現表)\n"
    "          - Columns: Corner_Number, Entry_Speed, Apex_Speed, Exit_Speed, Consistency\n"
    "      [CHART] Figure輸出：\n"
    "        • all_corners_heatmap.png (全彎道熱力圖)\n"
    "        • corner_consistency_radar.png (彎道一致性雷達圖)\n"
    "\n"
    "👥 全部車手分析模組 (功能21-24)\n"
    f"{'=' * 80}\n"
    "21. 👥 所有車手綜合分析 (All Drivers Comprehensive Analysis)\n"
    "    功能描述：全賽事20位車手的綜合表現分析\n"
    "    輸入參數：年份、賽事、賽段類型\n"
    "    主要輸出：\n"
    "      [STATS] Table格式：\n"
    "        • All_Drivers_Summary (全車手摘要表)\n"
    "          - Columns: Driver, Position, BestLap, AverageLap, Consistency, Points\n"
    "        • Championship_Impact (冠軍積分影響表)\n"
    "          - Columns: Driver, PointsGained, ChampionshipPosition, PositionChange\n"
    "      [CHART] Figure輸出：\n"
    "        • drivers_performance_comparison.png (車手表現對比圖)\n"
    "        • championship_standings.png (冠軍積分榜)\n"
    "\n"
    "22. [F1] 彎道速度分析 (Corner Speed Analysis)\n"
    "    ⚠️  狀態：已棄用 (DEPRECATED)\n"
    "    功能描述：分析賽道各彎道的速度表現\n"
    "    輸入參數：年份、賽事、賽段類型\n"
    "    主要輸出：\n"
    "      [STATS] Table格式：\n"
    "        • Corner_Speed_Ranking (彎道速度排名表)\n"
    "          - Columns: Corner, FastestDriver, Speed, AverageSpeed, SpeedVariation\n"
    "\n"
    "23. [START] 全部車手超車分析 (All Drivers Overtaking)\n"
    "    功能描述：全賽事所有超車事件的綜合分析\n"
    "    輸入參數：年份、賽事、賽段類型\n"
    "    主要輸出：\n"
    "      [STATS] Table格式：\n"
    "        • All_Overtaking_Events (全部超車事件表)\n"
    "          - Columns: LapNumber, Driver1, Driver2, Location, Type, Success\n"
    "        • Overtaking_Statistics (超車統計表)\n"
    "          - Columns: Driver, Total_Overtakes, Success_Rate, Best_Overtaking_Zone\n"
    "      [CHART] Figure輸出：\n"
    "        • race_overtaking_map.png (賽事超車地圖)\n"
    "        • overtaking_statistics.png (超車統計圖)\n"
    "      [SAVE] 暫存檔案：overtaking_cache/目錄中的JSON檔案\n"
    "\n"
    "24. [STATS] 全部車手DNF分析 (All Drivers DNF Analysis)\n"
    "    功能描述：分析所有未完賽車手的退賽原因\n"
    "    輸入參數：年份、賽事、賽段類型\n"
    "    主要輸出：\n"
    "      [STATS] Table格式：\n"
    "        • DNF_Summary (DNF摘要表)\n"
    "          - Columns: Driver, DNF_Reason, LapNumber, Position_Lost, Impact_Score\n"
    "        • Reliability_Analysis (可靠性分析表)\n"
    "          - Columns: Team, DNF_Count, Main_Issues, Reliability_Rating\n"
    "      [CHART] Figure輸出：\n"
    "        • dnf_reasons_distribution.png (DNF原因分布圖)\n"
    "        • team_reliability_ranking.png (車隊可靠性排名)\n"
    "      [SAVE] 暫存檔案：dnf_analysis_cache/目錄中的TXT和PNG檔案\n"
    "\n"
    "🏆 全部車手全年分析模組 (選項14-15)\n"
    f"{'=' * 80}\n"
    "14. [START] 全部車手超車分析 (All Drivers Overtaking)\n"
    "    功能描述：全賽事所有超車事件的綜合分析\n"
    "    輸入參數：年份、賽事、賽段類型\n"
    "    主要輸出：\n"
    "      [STATS] Table格式：\n"
    "        • All_Overtaking_Events (全部超車事件表)\n"
    "          - Columns: LapNumber, Driver1, Driver2, Location, Type, Success\n"
    "        • Overtaking_Statistics (超車統計表)\n"
    "          - Columns: Driver, Total_Overtakes, Success_Rate, Best_Overtaking_Zone\n"
    "      [CHART] Figure輸出：\n"
    "        • race_overtaking_map.png (賽事超車地圖)\n"
    "        • overtaking_statistics.png (超車統計圖)\n"
    "      [SAVE] 暫存檔案：overtaking_cache/目錄中的JSON檔案\n"
    "\n"
    "15. [STATS] 獨立全部車手DNF分析 (Independent All Drivers DNF)\n"
    "    功能描述：分析所有未完賽車手的退賽原因\n"
    "    輸入參數：年份、賽事、賽段類型\n"
    "    主要輸出：\n"
    "      [STATS] Table格式：\n"
    "        • DNF_Summary (DNF摘要表)\n"
    "          - Columns: Driver, DNF_Reason, LapNumber, Position_Lost, Impact_Score\n"
    "        • Reliability_Analysis (可靠性分析表)\n"
    "          - Columns: Team, DNF_Count, Main_Issues, Reliability_Rating\n"
    "      [CHART] Figure輸出：\n"
    "        • dnf_reasons_distribution.png (DNF原因分布圖)\n"
    "        • team_reliability_ranking.png (車隊可靠性排名)\n"
    "      [SAVE] 暫存檔案：dnf_analysis_cache/目錄中的TXT和PNG檔案\n"
    "\n"
    "[TOOL] 系統功能 (功能49-53)\n"
    f"{'=' * 80}\n"
    "49. [REFRESH] 數據匯出管理器 (Data Export Manager)\n"
    "    功能描述：管理數據匯出功能\n"
    "    輸入參數：匯出選項\n"
    "    主要輸出：匯出的數據檔案\n"
    "\n"
    "50. [CACHE] 快取優化 (Cache Optimization)\n"
    "    功能描述：優化系統快取性能\n"
    "    輸入參數：優化參數\n"
    "    主要輸出：優化報告\n"
    "\n"
    "51. [DIAG] 系統診斷 (System Diagnostics)\n"
    "    功能描述：檢查系統狀態和診斷問題\n"
    "    輸入參數：診斷選項\n"
    "    主要輸出：診斷報告\n"
    "\n"
    "52. [PERF] 性能基準測試 (Performance Benchmarking)\n"
    "    功能描述：測試系統性能\n"
    "    輸入參數：測試參數\n"
    "    主要輸出：性能報告\n"
    "\n"
    "53. [CHECK] 數據完整性檢查 (Data Integrity Check)\n"
    "    功能描述：檢查數據完整性\n"
    "    輸入參數：檢查參數\n"
    "    主要輸出：完整性報告\n"
    "\n"
    "[SETTINGS]  設定功能 (字母選項)\n"
    f"{'=' * 80}\n"
    "S.  [SETTINGS] 重新設定賽事參數 (Change Race Settings)\n"
    "    功能描述：使用新參數重新設定分析的賽事參數\n"
    "    輸入參數：年份、賽事、賽段參數\n"
    "\n"
    "L.  [INFO] 列出支援的賽事 (List Supported Races)\n"
    "    功能描述：顯示2024-2025年支援的所有賽事\n"
    "    輸入參數：可選年份\n"
    "\n"
    "C.  [CHECK] 暫存狀態檢查 (Check Cache Status)\n"
    "    功能描述：檢查所有暫存目錄的狀態\n"
    "    輸入參數：無\n"
    "\n"
    "D.  [CHECK] DNF暫存檢查 (Check DNF Cache)\n"
    "    功能描述：檢查DNF分析暫存的詳細狀態\n"
    "    輸入參數：無\n"
    "\n"
    "[NOTE] 輸出檔案命名規則\n"
    f"{'=' * 80}\n"
    "• Table檔案：CSV格式，檔名包含分析類型和時間戳\n"
    "• Figure檔案：PNG格式，高解析度，支援中文字體\n"
    "• 暫存檔案：JSON/TXT格式，包含完整分析數據\n"
    "• 檔名格式：{year}_{race}_{analysis_type}_{timestamp}\n"
    "\n"
    "[TOOL] 技術架構與數據流\n"
    f"{'=' * 80}\n"
    "• 數據來源：FastF1官方API + OpenF1即時數據\n"
    "• 處理流程：數據載入 → 清理驗證 → 分析計算 → 輸出生成\n"
    "• 暫存機制：自動暫存計算結果，避免重複載入\n"
    "• 錯誤處理：每個模組獨立錯誤處理，確保系統穩定性\n"
    "\n"
    "[WARNING]  重要注意事項\n"
    f"{'=' * 80}\n"
    "• 網路需求：需要穩定網路連接以獲取F1數據\n"
    "• 資料完整性：較新賽事數據完整性較高，建議優先分析\n"
    "• 練習賽限制：練習賽數據可能不完整，建議使用正賽數據\n"
    "• 暫存管理：定期清理暫存檔案以節省磁碟空間\n"
    f"{'=' * 80}\n"
    "💡 快速開始：輸入功能編號(1-24, 49-53)或子功能編號開始分析，輸入0退出\n"
    "[REFRESH] 更新日期：2025年9月6日 | 版本：v5.4 (映射表同步版)\n"
    f"{'=' * 80}"
)

_EN_US_HELP_TEXT = (
    "\n"
    "📖 F1 Analysis CLI - Modular Edition User Guide (v5.4 CLI Only)\n"
    f"{'=' * 80}\n"
    "This is the fully modular F1 analysis system designed for parameter-only CLI execution.\n"
    "It leverages FastF1 and OpenF1 official APIs and covers 2024-2025 race telemetry.\n"
    "✨ Highlight: Enhanced race picker now shows event dates and full Grand Prix titles.\n"
    "\n"
    "[FINISH] Race Selection Enhancements\n"
    f"{'─' * 80}\n"
    "• [CALENDAR] Displays the exact date for every round.\n"
    "• 🏆 Shows the full official Grand Prix name.\n"
    "• [STATS] Clear, tabular schedule overview.\n"
    "• 🌍 Complete coverage for the 2024-2025 seasons.\n"
    "\n"
    "[RAIN]  Core Analysis Modules (Functions 1-10)\n"
    f"{'=' * 80}\n"
    "1.  [RAIN] Enhanced Rain Intensity Analysis\n"
    "    Summary: FastF1-driven rainfall analytics with structured JSON output.\n"
    "    Inputs: year, race, session.\n"
    "    Key outputs:\n"
    "      [JSON] Structured data sets:\n"
    "        • temperature_vs_lap\n"
    "        • rain_vs_lap\n"
    "        • humidity_vs_lap\n"
    "        • windspeed_vs_lap\n"
    "        • pressure_vs_lap\n"
    "      [CACHE] Integrated pickle-based cache support.\n"
    "      [NOTE] Uses the enhanced rain analyzer (CLI_modules/cli/analyzer/weather/rain_analyzer.py).\n"
    "\n"
    "2.  [TRACK] Track Path Analysis\n"
    "    Summary: Evaluates racing lines and optimal trajectories.\n"
    "    Inputs: year, race, session, optional driver selection.\n"
    "    Key outputs:\n"
    "      [STATS] Tables:\n"
    "        • Track_Path_Coordinates (X, Y, Z, Speed, Distance, Sector).\n"
    "        • Racing_Line_Analysis (CornerNumber, OptimalSpeed, ActualSpeed, LineDifference).\n"
    "      [CHART] Figures:\n"
    "        • track_layout_with_paths.png\n"
    "        • racing_line_heatmap.png\n"
    "        • speed_zones_visualization.png\n"
    "\n"
    "3.  [PIT] Driver Fastest Pitstop Ranking\n"
    "    Summary: Highlights each driver's quickest stop.\n"
    "    Inputs: year, race, session.\n"
    "    Key outputs: Pitstop_Time_Ranking table (Driver, FastestPitstop, AveragePitstop, PitstopCount).\n"
    "\n"
    "4.  [PIT] Team Pitstop Ranking\n"
    "    Summary: Aggregates pit performance per team.\n"
    "    Inputs: year, race, session.\n"
    "    Key outputs: Team_Pitstop_Ranking table (Team, AveragePitstop, BestPitstop, PitstopCount).\n"
    "\n"
    "5.  [PIT] Driver Detailed Pitstop Records\n"
    "    Summary: Lap-by-lap pit records for a chosen driver.\n"
    "    Inputs: year, race, session, driver code.\n"
    "    Key outputs: Pitstop_Details table (LapNumber, PitstopTime, TyreCompound, PositionChange).\n"
    "\n"
    "6.  💥 Accident Statistics Summary\n"
    "    Summary: Overall incident snapshot for the race.\n"
    "    Inputs: year, race, session.\n"
    "    Key outputs: Accident_Summary table (TotalAccidents, DriversInvolved, Locations, SeverityLevels).\n"
    "\n"
    "7.  💥 Severity Distribution Analysis\n"
    "    Summary: Breakdown of incident severity levels.\n"
    "    Inputs: year, race, session.\n"
    "    Key outputs: Severity_Distribution table (SeverityLevel, Count, Percentage, MostCommonLocation).\n"
    "\n"
    "8.  💥 All Incidents Summary\n"
    "    Summary: Full incident log with context.\n"
    "    Inputs: year, race, session.\n"
    "    Key outputs: All_Incidents_List (Time, IncidentType, Drivers, Location, Details).\n"
    "\n"
    "9.  💥 Special Incident Reports\n"
    "    Summary: Focus on noteworthy or unusual events.\n"
    "    Inputs: year, race, session.\n"
    "    Key outputs: Special_Incidents table (IncidentType, Time, Drivers, Impact, Details).\n"
    "\n"
    "10. 💥 Key Events Summary\n"
    "    Summary: Condensed recap of pivotal race moments.\n"
    "    Inputs: year, race, session.\n"
    "    Key outputs: Key_Events_Summary (EventType, Time, Description, RaceImpact).\n"
    "\n"
    "[F1] Single-Driver Modules (Functions 11-20)\n"
    f"{'=' * 80}\n"
    "11. [F1] Single Driver Comprehensive Analysis (Deprecated)\n"
    "    Summary: Legacy full driver review, retained for compatibility.\n"
    "    Inputs: year, race, session, driver code.\n"
    "    Key outputs: Driver_Performance_Summary (LapNumber, LapTime, Position, SectorTimes, Speed).\n"
    "\n"
    "12. 📡 Single Driver Detailed Telemetry\n"
    "    Summary: Deep dive telemetry for one driver.\n"
    "    Inputs: year, race, session, driver, lap selection.\n"
    "    Key outputs:\n"
    "      Telemetry_Data table (Distance, Speed, Throttle, Brake, Gear, RPM, DRS).\n"
    "      Performance_Metrics table (Metric, Value, OptimalValue, Difference, Percentage).\n"
    "      Charts: speed_trace, throttle_brake_analysis, gear_shift_patterns.\n"
    "\n"
    "13. [BALANCE] Driver Comparison\n"
    "    Summary: Lap-by-lap duel between two drivers.\n"
    "    Inputs: year, race, session, driver1, driver2.\n"
    "    Key outputs: Driver_Comparison_Table and Lap_by_Lap_Comparison, plus comparison charts.\n"
    "\n"
    "14. [CHART] Race Position Changes (Deprecated)\n"
    "    Summary: Visualises position evolution across the race.\n"
    "    Inputs: year, race, session.\n"
    "    Key outputs: position_changes_chart.png.\n"
    "\n"
    "15. [START] Race Overtaking Statistics\n"
    "    Summary: Aggregated overtaking stats for a race.\n"
    "    Inputs: year, race, session.\n"
    "    Key outputs: Overtaking_Statistics table (TotalOvertakes, Successful, Failed, KeyMoments).\n"
    "\n"
    "16. [FINISH] Single Driver Overtaking\n"
    "    Summary: Full overtaking profile (made/defended) for one driver.\n"
    "    Inputs: year, race, session, driver.\n"
    "    Key outputs: Overtaking_Events & Overtaking_Statistics tables, plus overtaking timeline and zone maps.\n"
    "\n"
    "17. [TARGET] Dynamic Corner Detection (New)\n"
    "    Summary: Auto-detects corners and measures entry/apex/exit context.\n"
    "    Inputs: year, race, session.\n"
    "    Key outputs: Corner_Detection_Results table (CornerNumber, StartPoint, EndPoint, Radius, Speed).\n"
    "\n"
    "18. [TARGET] Corner Detailed Analysis\n"
    "    Summary: For a selected corner, inspect driver performance.\n"
    "    Inputs: year, race, session, corner number.\n"
    "    Key outputs: Corner_Performance & Corner_Statistics tables, plus progression charts.\n"
    "\n"
    "19. [TOOL] Single Driver DNF Analysis\n"
    "    Summary: Reliability profile for a particular driver.\n"
    "    Inputs: year, race, session, driver.\n"
    "    Key outputs: DNF_Analysis & Reliability_Metrics tables, plus performance/failure graphs.\n"
    "\n"
    "20. [TARGET] Single Driver All Corners\n"
    "    Summary: Consistency metrics across every corner.\n"
    "    Inputs: year, race, session, driver.\n"
    "    Key outputs: All_Corners_Performance table and heatmap/radar charts.\n"
    "\n"
    "👥 All-Drivers Modules (Functions 21-24)\n"
    f"{'=' * 80}\n"
    "21. 👥 All Drivers Comprehensive Analysis\n"
    "    Summary: Overview of the full grid’s performance.\n"
    "    Inputs: year, race, session.\n"
    "    Key outputs: All_Drivers_Summary and Championship_Impact tables; comparison and standings charts.\n"
    "\n"
    "22. [F1] Corner Speed Analysis (Deprecated)\n"
    "    Summary: Legacy per-corner speed ranking.\n"
    "    Inputs: year, race, session.\n"
    "    Key outputs: Corner_Speed_Ranking table.\n"
    "\n"
    "23. [START] All Drivers Overtaking\n"
    "    Summary: Entire grid’s overtaking events with statistics and visuals.\n"
    "    Inputs: year, race, session.\n"
    "    Key outputs: All_Overtaking_Events & Overtaking_Statistics tables, plus maps/plots.\n"
    "    Cache: JSON artefacts in overtaking_cache/.\n"
    "\n"
    "24. [STATS] All Drivers DNF Analysis\n"
    "    Summary: Reliability snapshot across all non-finishers.\n"
    "    Inputs: year, race, session.\n"
    "    Key outputs: DNF_Summary and Reliability_Analysis tables, with distribution and ranking charts.\n"
    "    Cache: TXT/PNG artefacts in dnf_analysis_cache/.\n"
    "\n"
    "🏆 Full-Season Utilities (Options 14-15)\n"
    f"{'=' * 80}\n"
    "14. [START] Full-Season Overtaking Overview\n"
    "    Summary: Aggregated overtaking metrics across the season.\n"
    "    Inputs: year, race, session.\n"
    "    Outputs mirror function 23 (statistics, maps, cache).\n"
    "\n"
    "15. [STATS] Independent Full-Season DNF Analysis\n"
    "    Summary: Dedicated reliability deep dive for non-finishers.\n"
    "    Inputs: year, race, session.\n"
    "    Outputs mirror function 24 (tables, charts, cache).\n"
    "\n"
    "[TOOL] System Utilities (Functions 49-53)\n"
    f"{'=' * 80}\n"
    "49. [REFRESH] Data Export Manager — orchestrates export pipelines.\n"
    "50. [CACHE] Cache Optimisation — maintenance of local caches.\n"
    "51. [DIAG] System Diagnostics — health / troubleshooting checks.\n"
    "52. [PERF] Performance Benchmarking — runtime benchmarking suite.\n"
    "53. [CHECK] Data Integrity Check — validates cached artefacts.\n"
    "\n"
    "[SETTINGS]  Letter Commands\n"
    f"{'=' * 80}\n"
    "S.  [SETTINGS] Change Race Settings — reconfigure current analysis context.\n"
    "L.  [INFO] List Supported Races — shows supported events for 2024-2025.\n"
    "C.  [CHECK] Check Cache Status — inspect all cache locations.\n"
    "D.  [CHECK] Check DNF Cache — detailed DNF cache diagnostics.\n"
    "\n"
    "[NOTE] Output Naming\n"
    f"{'=' * 80}\n"
    "• Tables: CSV files with analysis type and timestamp.\n"
    "• Figures: High-resolution PNG with CJK font support.\n"
    "• Cache: JSON/TXT artefacts storing intermediate results.\n"
    "• Filename schema: {year}_{race}_{analysis_type}_{timestamp}.\n"
    "\n"
    "[TOOL] Data Flow & Architecture\n"
    f"{'=' * 80}\n"
    "• Sources: FastF1 HTTP cache + OpenF1 live feeds.\n"
    "• Pipeline: Load → Validate → Analyse → Persist.\n"
    "• Cache: Automatic reuse to avoid redundant downloads.\n"
    "• Errors: Module-level error handling preserves stability.\n"
    "\n"
    "[WARNING]  Key Reminders\n"
    f"{'=' * 80}\n"
    "• Connectivity: Stable internet required for live data.\n"
    "• Data freshness: Recent rounds have the highest completeness.\n"
    "• Practice limitations: FP sessions can be sparse—prefer race data.\n"
    "• Cache hygiene: Clean caches periodically to save disk space.\n"
    f"{'=' * 80}\n"
    "💡 Quick start: provide a function ID (1-24, 49-53) or sub-ID to run analysis; enter 0 to exit.\n"
    "[REFRESH] Updated: 2025-09-06 | Version: v5.4 (mapping-synchronised edition).\n"
    f"{'=' * 80}"
)

CLI_HELP_LINES = {
    "zh-TW": _ZH_TW_HELP_TEXT.splitlines(),
    "en-US": _EN_US_HELP_TEXT.splitlines(),
}


def get_cli_help_lines(language: str | None = None) -> List[str]:
    """Return the help lines for the requested language."""
    resolved = resolve_cli_language(language)
    return list(CLI_HELP_LINES.get(resolved, CLI_HELP_LINES["zh-TW"]))


def iter_cli_help_lines(language: str | None = None) -> Iterable[str]:
    """Yield help lines lazily for streaming to stdout."""
    for line in get_cli_help_lines(language):
        yield line
