#!/usr/bin/env python3
"""
Race weather forecast generator (-f96).

This module mirrors the smart-refresh workflow used by Function 99 (season calendar)
while producing weather forecasts and contextual history for a target Grand Prix.
It relies on Open-Meteo's free APIs (forecast + archive) and the multi-year season
calendar JSON generated by -f99 to determine the latest race information.
"""

from __future__ import annotations

import json
import unicodedata
from datetime import date, datetime, timedelta, timezone
from pathlib import Path
from typing import Any, Callable, Dict, Iterable, List, Optional, Tuple

import requests

from CLI_modules.cli.analyzer.season_calendar_analysis import (
    check_calendar_freshness,
    generate_season_calendar,
)
from CLI_modules.cli.core.json_output_config import (
    ANALYSIS_TYPE_DIRECTORIES,
    BASE_JSON_DIR,
    get_json_output_path,
)

RaceWeatherResult = Dict[str, Any]
HttpGetter = Callable[..., requests.Response]

# Open-Meteo endpoints
OPEN_METEO_FORECAST_URL = "https://api.open-meteo.com/v1/forecast"
OPEN_METEO_ARCHIVE_URL = "https://archive-api.open-meteo.com/v1/archive"

# Default refresh cadence (hours) – matches the season calendar behaviour
WEATHER_REFRESH_HOURS = 24  # 1 天 (平時維護模式)

# Variable selections
FORECAST_HOURLY_VARS = (
    "temperature_2m,precipitation,precipitation_probability,cloudcover,"
    "windspeed_10m,winddirection_10m"
)
FORECAST_DAILY_VARS = (
    "temperature_2m_max,temperature_2m_min,precipitation_sum,cloudcover_mean,"
    "windspeed_10m_max,winddirection_10m_dominant"
)
ARCHIVE_HOURLY_VARS = "temperature_2m,precipitation,cloudcover,windspeed_10m,winddirection_10m"
ARCHIVE_DAILY_VARS = (
    "temperature_2m_max,temperature_2m_min,precipitation_sum,cloudcover_mean,"
    "windspeed_10m_max,winddirection_10m_dominant"
)


def _normalise_key(value: Optional[str]) -> str:
    if not value:
        return ""
    normalised = unicodedata.normalize("NFKD", value)
    ascii_only = "".join(ch for ch in normalised if ch.isascii())
    return ascii_only.strip().lower()


def _slugify(value: str) -> str:
    """
    Convert a race/event name into a filesystem-friendly token.
    """
    normalised = unicodedata.normalize("NFKD", value)
    ascii_only = "".join(ch for ch in normalised if ch.isascii())
    filtered = "".join(ch if ch.isalnum() else "_" for ch in ascii_only.strip().lower())
    while "__" in filtered:
        filtered = filtered.replace("__", "_")
    return filtered.strip("_") or "unknown"


# ---------------------------------------------------------------------------
# Static circuit metadata (coordinates + timezone)
# ---------------------------------------------------------------------------
_BASE_CIRCUIT_DATA: Dict[str, Dict[str, Any]] = {
    "Abu Dhabi Grand Prix": {
        "latitude": 24.4672,
        "longitude": 54.6031,
        "timezone": "Asia/Dubai",
        "circuit": "Yas Marina Circuit",
        "country": "United Arab Emirates",
    },
    "Australian Grand Prix": {
        "latitude": -37.8497,
        "longitude": 144.9680,
        "timezone": "Australia/Melbourne",
        "circuit": "Albert Park Circuit",
        "country": "Australia",
    },
    "Austrian Grand Prix": {
        "latitude": 47.2190,
        "longitude": 14.7640,
        "timezone": "Europe/Vienna",
        "circuit": "Red Bull Ring",
        "country": "Austria",
    },
    "Azerbaijan Grand Prix": {
        "latitude": 40.3725,
        "longitude": 49.8533,
        "timezone": "Asia/Baku",
        "circuit": "Baku City Circuit",
        "country": "Azerbaijan",
    },
    "Bahrain Grand Prix": {
        "latitude": 26.0325,
        "longitude": 50.5106,
        "timezone": "Asia/Bahrain",
        "circuit": "Bahrain International Circuit",
        "country": "Bahrain",
    },
    "Belgian Grand Prix": {
        "latitude": 50.4372,
        "longitude": 5.9714,
        "timezone": "Europe/Brussels",
        "circuit": "Circuit de Spa-Francorchamps",
        "country": "Belgium",
    },
    "British Grand Prix": {
        "latitude": 52.0786,
        "longitude": -1.0169,
        "timezone": "Europe/London",
        "circuit": "Silverstone Circuit",
        "country": "United Kingdom",
    },
    "Canadian Grand Prix": {
        "latitude": 45.5017,
        "longitude": -73.5228,
        "timezone": "America/Toronto",
        "circuit": "Circuit Gilles Villeneuve",
        "country": "Canada",
    },
    "Chinese Grand Prix": {
        "latitude": 31.3389,
        "longitude": 121.2206,
        "timezone": "Asia/Shanghai",
        "circuit": "Shanghai International Circuit",
        "country": "China",
    },
    "Dutch Grand Prix": {
        "latitude": 52.3889,
        "longitude": 4.5409,
        "timezone": "Europe/Amsterdam",
        "circuit": "Circuit Zandvoort",
        "country": "Netherlands",
    },
    "Eifel Grand Prix": {
        "latitude": 50.3356,
        "longitude": 6.9475,
        "timezone": "Europe/Berlin",
        "circuit": "Nürburgring",
        "country": "Germany",
    },
    "Emilia Romagna Grand Prix": {
        "latitude": 44.3439,
        "longitude": 11.7167,
        "timezone": "Europe/Rome",
        "circuit": "Autodromo Enzo e Dino Ferrari (Imola)",
        "country": "Italy",
    },
    "French Grand Prix": {
        "latitude": 43.2506,
        "longitude": 5.7917,
        "timezone": "Europe/Paris",
        "circuit": "Circuit Paul Ricard",
        "country": "France",
    },
    "Hungarian Grand Prix": {
        "latitude": 47.5789,
        "longitude": 19.2481,
        "timezone": "Europe/Budapest",
        "circuit": "Hungaroring",
        "country": "Hungary",
    },
    "Italian Grand Prix": {
        "latitude": 45.6156,
        "longitude": 9.2811,
        "timezone": "Europe/Rome",
        "circuit": "Autodromo Nazionale Monza",
        "country": "Italy",
    },
    "Japanese Grand Prix": {
        "latitude": 34.8431,
        "longitude": 136.5411,
        "timezone": "Asia/Tokyo",
        "circuit": "Suzuka International Racing Course",
        "country": "Japan",
    },
    "Las Vegas Grand Prix": {
        "latitude": 36.1147,
        "longitude": -115.1730,
        "timezone": "America/Los_Angeles",
        "circuit": "Las Vegas Strip Circuit",
        "country": "United States",
    },
    "Mexico City Grand Prix": {
        "latitude": 19.4042,
        "longitude": -99.0907,
        "timezone": "America/Mexico_City",
        "circuit": "Autódromo Hermanos Rodríguez",
        "country": "Mexico",
    },
    "Miami Grand Prix": {
        "latitude": 25.9581,
        "longitude": -80.2389,
        "timezone": "America/New_York",
        "circuit": "Miami International Autodrome",
        "country": "United States",
    },
    "Monaco Grand Prix": {
        "latitude": 43.7347,
        "longitude": 7.4206,
        "timezone": "Europe/Monaco",
        "circuit": "Circuit de Monaco",
        "country": "Monaco",
    },
    "Portuguese Grand Prix": {
        "latitude": 37.2273,
        "longitude": -8.6267,
        "timezone": "Europe/Lisbon",
        "circuit": "Autódromo Internacional do Algarve (Portimão)",
        "country": "Portugal",
    },
    "Qatar Grand Prix": {
        "latitude": 25.4917,
        "longitude": 51.4542,
        "timezone": "Asia/Qatar",
        "circuit": "Lusail International Circuit",
        "country": "Qatar",
    },
    "Russian Grand Prix": {
        "latitude": 43.4027,
        "longitude": 39.9578,
        "timezone": "Europe/Moscow",
        "circuit": "Sochi Autodrom",
        "country": "Russia",
    },
    "Sakhir Grand Prix": {
        "latitude": 26.0325,
        "longitude": 50.5106,
        "timezone": "Asia/Bahrain",
        "circuit": "Bahrain International Circuit (Outer)",
        "country": "Bahrain",
    },
    "Saudi Arabian Grand Prix": {
        "latitude": 21.6319,
        "longitude": 39.1044,
        "timezone": "Asia/Riyadh",
        "circuit": "Jeddah Corniche Circuit",
        "country": "Saudi Arabia",
    },
    "Singapore Grand Prix": {
        "latitude": 1.2914,
        "longitude": 103.8631,
        "timezone": "Asia/Singapore",
        "circuit": "Marina Bay Street Circuit",
        "country": "Singapore",
    },
    "Spanish Grand Prix": {
        "latitude": 41.5700,
        "longitude": 2.2610,
        "timezone": "Europe/Madrid",
        "circuit": "Circuit de Barcelona-Catalunya",
        "country": "Spain",
    },
    "Styrian Grand Prix": {
        "latitude": 47.2190,
        "longitude": 14.7640,
        "timezone": "Europe/Vienna",
        "circuit": "Red Bull Ring",
        "country": "Austria",
    },
    "São Paulo Grand Prix": {
        "latitude": -23.7036,
        "longitude": -46.6997,
        "timezone": "America/Sao_Paulo",
        "circuit": "Autódromo José Carlos Pace (Interlagos)",
        "country": "Brazil",
    },
    "Turkish Grand Prix": {
        "latitude": 40.9517,
        "longitude": 29.4050,
        "timezone": "Europe/Istanbul",
        "circuit": "Istanbul Park",
        "country": "Turkey",
    },
    "Tuscan Grand Prix": {
        "latitude": 43.9981,
        "longitude": 11.3719,
        "timezone": "Europe/Rome",
        "circuit": "Autodromo Internazionale del Mugello",
        "country": "Italy",
    },
    "United States Grand Prix": {
        "latitude": 30.1328,
        "longitude": -97.6411,
        "timezone": "America/Chicago",
        "circuit": "Circuit of the Americas",
        "country": "United States",
    },
    "70th Anniversary Grand Prix": {
        "latitude": 52.0786,
        "longitude": -1.0169,
        "timezone": "Europe/London",
        "circuit": "Silverstone Circuit",
        "country": "United Kingdom",
    },
}

_LOCATION_ALIASES: Dict[str, str] = {
    "austin": "United States Grand Prix",
    "baku": "Azerbaijan Grand Prix",
    "barcelona": "Spanish Grand Prix",
    "budapest": "Hungarian Grand Prix",
    "imola": "Emilia Romagna Grand Prix",
    "istanbul": "Turkish Grand Prix",
    "jeddah": "Saudi Arabian Grand Prix",
    "las vegas": "Las Vegas Grand Prix",
    "le castellet": "French Grand Prix",
    "lusail": "Qatar Grand Prix",
    "marina bay": "Singapore Grand Prix",
    "melbourne": "Australian Grand Prix",
    "mexico city": "Mexico City Grand Prix",
    "miami": "Miami Grand Prix",
    "miami gardens": "Miami Grand Prix",
    "monaco": "Monaco Grand Prix",
    "monte carlo": "Monaco Grand Prix",
    "montréal": "Canadian Grand Prix",
    "montreal": "Canadian Grand Prix",
    "monza": "Italian Grand Prix",
    "mugello": "Tuscan Grand Prix",
    "nürburgring": "Eifel Grand Prix",
    "nurburgring": "Eifel Grand Prix",
    "portimão": "Portuguese Grand Prix",
    "portimao": "Portuguese Grand Prix",
    "sakhir": "Bahrain Grand Prix",
    "shanghai": "Chinese Grand Prix",
    "silverstone": "British Grand Prix",
    "sochi": "Russian Grand Prix",
    "spa-francorchamps": "Belgian Grand Prix",
    "spielberg": "Austrian Grand Prix",
    "suzuka": "Japanese Grand Prix",
    "são paulo": "São Paulo Grand Prix",
    "sao paulo": "São Paulo Grand Prix",
    "yas island": "Abu Dhabi Grand Prix",
    "zandvoort": "Dutch Grand Prix",
}

_EVENT_COORDINATES = {
    _normalise_key(name): data for name, data in _BASE_CIRCUIT_DATA.items()
}

_LOCATION_COORDINATES: Dict[str, Dict[str, Any]] = {}
for raw_alias, target_event in _LOCATION_ALIASES.items():
    alias_key = _normalise_key(raw_alias)
    target_key = _normalise_key(target_event)
    if target_key in _EVENT_COORDINATES:
        _LOCATION_COORDINATES[alias_key] = _EVENT_COORDINATES[target_key]


WEATHER_SUBDIR = ANALYSIS_TYPE_DIRECTORIES.get("race_weather_forecast", "weather")
WEATHER_OUTPUT_DIR = Path(BASE_JSON_DIR) / WEATHER_SUBDIR


# ---------------------------------------------------------------------------
# Helper utilities
# ---------------------------------------------------------------------------
def _resolve_circuit(event_name: Optional[str], location: Optional[str]) -> Dict[str, Any]:
    event_key = _normalise_key(event_name)
    if event_key and event_key in _EVENT_COORDINATES:
        return _EVENT_COORDINATES[event_key]

    location_key = _normalise_key(location)
    if location_key and location_key in _LOCATION_COORDINATES:
        return _LOCATION_COORDINATES[location_key]

    raise KeyError(
        f"Unable to resolve coordinates for event={event_name!r}, location={location!r}"
    )


def _wind_direction_to_cardinal(degrees: Optional[float]) -> Optional[str]:
    if degrees is None:
        return None
    bearings = ["N", "NE", "E", "SE", "S", "SW", "W", "NW"]
    idx = int((float(degrees) % 360) / 45 + 0.5) % len(bearings)
    return bearings[idx]


def _extract_hourly_block(hourly: Dict[str, List[Any]], target_date: date) -> List[Dict[str, Any]]:
    times = hourly.get("time") or []
    if not times:
        return []

    results: List[Dict[str, Any]] = []
    fields = {
        "temperature_2m": hourly.get("temperature_2m") or [],
        "precipitation": hourly.get("precipitation") or [],
        "precipitation_probability": hourly.get("precipitation_probability"),
        "cloudcover": hourly.get("cloudcover") or [],
        "windspeed_10m": hourly.get("windspeed_10m") or [],
        "winddirection_10m": hourly.get("winddirection_10m") or [],
    }

    for index, time_str in enumerate(times):
        try:
            dt = datetime.fromisoformat(time_str)
        except ValueError:
            continue
        if dt.date() != target_date:
            continue

        entry: Dict[str, Any] = {"time": time_str}
        entry["temperature_2m"] = _safe_index(fields["temperature_2m"], index)
        entry["precipitation"] = _safe_index(fields["precipitation"], index)
        if fields["precipitation_probability"] is not None:
            entry["precipitation_probability"] = _safe_index(
                fields["precipitation_probability"], index
            )
        entry["cloudcover"] = _safe_index(fields["cloudcover"], index)
        entry["windspeed_10m"] = _safe_index(fields["windspeed_10m"], index)
        wind_dir = _safe_index(fields["winddirection_10m"], index)
        entry["winddirection_10m"] = wind_dir
        entry["winddirection_cardinal"] = (
            _wind_direction_to_cardinal(wind_dir) if wind_dir is not None else None
        )
        results.append(entry)

    return results


def _safe_index(sequence: Iterable[Any], index: int) -> Optional[Any]:
    if isinstance(sequence, list):
        if 0 <= index < len(sequence):
            return sequence[index]
        return None
    try:
        seq_list = list(sequence)
        if 0 <= index < len(seq_list):
            return seq_list[index]
    except TypeError:
        pass
    return None


def _build_daily_entry(
    label: str,
    target_date: date,
    daily: Dict[str, List[Any]],
    hourly: Dict[str, List[Any]],
    daily_units: Dict[str, Any],
) -> Dict[str, Any]:
    summary: Dict[str, Any] = {}
    day_str = target_date.isoformat()
    times = daily.get("time") or []
    idx = next((i for i, value in enumerate(times) if value == day_str), None)

    if idx is not None:
        summary["temperature_max"] = _safe_index(daily.get("temperature_2m_max") or [], idx)
        summary["temperature_min"] = _safe_index(daily.get("temperature_2m_min") or [], idx)
        summary["precipitation_sum"] = _safe_index(daily.get("precipitation_sum") or [], idx)
        summary["cloudcover_mean"] = _safe_index(daily.get("cloudcover_mean") or [], idx)
        summary["windspeed_max"] = _safe_index(daily.get("windspeed_10m_max") or [], idx)
        wind_dom = _safe_index(daily.get("winddirection_10m_dominant") or [], idx)
        summary["winddirection_dominant"] = wind_dom
        summary["winddirection_cardinal"] = (
            _wind_direction_to_cardinal(wind_dom) if wind_dom is not None else None
        )
    else:
        summary = {
            "temperature_max": None,
            "temperature_min": None,
            "precipitation_sum": None,
            "cloudcover_mean": None,
            "windspeed_max": None,
            "winddirection_dominant": None,
            "winddirection_cardinal": None,
        }

    return {
        "date": day_str,
        "label": label,
        "summary": summary,
        "hourly": _extract_hourly_block(hourly, target_date),
        "units": {
            "temperature_max": daily_units.get("temperature_2m_max"),
            "temperature_min": daily_units.get("temperature_2m_min"),
            "precipitation_sum": daily_units.get("precipitation_sum"),
            "cloudcover_mean": daily_units.get("cloudcover_mean"),
            "windspeed_max": daily_units.get("windspeed_10m_max"),
            "winddirection_dominant": daily_units.get("winddirection_10m_dominant"),
        },
    }


def _select_target_event(
    calendar_payload: Dict[str, Any],
    year: int,
    event_name: Optional[str],
) -> Dict[str, Any]:
    data = calendar_payload.get("data", {})
    events = data.get(str(year))
    if not events:
        raise ValueError(f"No calendar data available for year={year}")

    if event_name:
        needle = _normalise_key(event_name)
        for item in events:
            # Try exact match on event_name first
            if _normalise_key(item.get("event_name")) == needle:
                return item
            # Try partial match on event_name (e.g., "Mexico" matches "Mexico City Grand Prix")
            if needle in _normalise_key(item.get("event_name")):
                return item
            # Try match on country
            if _normalise_key(item.get("country")) == needle:
                return item
            # Try match on location
            if _normalise_key(item.get("location")) == needle:
                return item
        raise ValueError(f"Event {event_name!r} not found in calendar for year={year}")

    upcoming = [
        item for item in events if isinstance(item.get("days_until_race"), (int, float))
    ]
    upcoming = [item for item in upcoming if (item.get("days_until_race") or 0) >= 0]

    if upcoming:
        return min(upcoming, key=lambda item: item.get("days_until_race", 0))

    # Season finished – pick the most recent by race_date_utc
    def _parse_date(value: Optional[str]) -> datetime:
        if not value:
            return datetime.min.replace(tzinfo=timezone.utc)
        try:
            return datetime.fromisoformat(value)
        except ValueError:
            return datetime.min.replace(tzinfo=timezone.utc)

    return max(events, key=lambda item: _parse_date(item.get("race_date_utc")))


def _load_calendar_data(
    *,
    force_refresh: bool,
    calendar_data: Optional[Dict[str, Any]] = None,
) -> Tuple[Dict[str, Any], Optional[str], Dict[str, Any]]:
    if calendar_data is not None:
        return calendar_data, None, {"source": "injected"}

    freshness = check_calendar_freshness(all_years=True)

    needs_regen = (
        not freshness.get("exists")
        or freshness.get("should_regenerate", False)
        or force_refresh
    )

    if needs_regen:
        print("\n[INFO] Generating latest season calendar data for weather lookup...")
        generate_season_calendar(save_json=True, all_years=True, force=True)
        freshness = check_calendar_freshness(all_years=True)

    calendar_path = freshness.get("path")
    if not calendar_path:
        raise FileNotFoundError("Unable to locate season calendar JSON for weather analysis")

    with open(calendar_path, "r", encoding="utf-8") as handle:
        payload = json.load(handle)

    return payload, calendar_path, freshness


def _build_forecast_payload(
    *,
    lat: float,
    lon: float,
    timezone_id: str,
    start_date: date,
    end_date: date,
    http_get: HttpGetter,
) -> Dict[str, Any]:
    params = {
        "latitude": lat,
        "longitude": lon,
        "hourly": FORECAST_HOURLY_VARS,
        "daily": FORECAST_DAILY_VARS,
        "timezone": timezone_id,
        "start_date": start_date.isoformat(),
        "end_date": end_date.isoformat(),
    }
    response = http_get(OPEN_METEO_FORECAST_URL, params=params, timeout=30)
    response.raise_for_status()
    data = response.json()
    return {
        "source": OPEN_METEO_FORECAST_URL,
        "requested_parameters": params,
        "raw": data,
    }


def _build_archive_payload(
    *,
    lat: float,
    lon: float,
    timezone_id: str,
    start_date: date,
    end_date: date,
    http_get: HttpGetter,
) -> Dict[str, Any]:
    params = {
        "latitude": lat,
        "longitude": lon,
        "hourly": ARCHIVE_HOURLY_VARS,
        "daily": ARCHIVE_DAILY_VARS,
        "timezone": timezone_id,
        "start_date": start_date.isoformat(),
        "end_date": end_date.isoformat(),
    }
    response = http_get(OPEN_METEO_ARCHIVE_URL, params=params, timeout=30)
    response.raise_for_status()
    data = response.json()
    return {
        "source": OPEN_METEO_ARCHIVE_URL,
        "requested_parameters": params,
        "raw": data,
    }


def check_weather_forecast_freshness(
    year: Optional[int] = None,
    event_name: Optional[str] = None,
) -> Dict[str, Any]:
    """
    Inspect the JSON/weather directory for the latest race weather file.
    """
    if not WEATHER_OUTPUT_DIR.exists():
        return {
            "exists": False,
            "path": None,
            "age_hours": None,
            "age_formatted": None,
            "is_fresh": False,
            "should_regenerate": True,
            "refresh_interval_hours": WEATHER_REFRESH_HOURS,
            "reason": "weather output directory does not exist",
        }

    pattern = "race_weather_forecast_*.json"
    event_slug = None
    if event_name:
        event_slug = _slugify(event_name)
    if year is not None and event_slug:
        pattern = f"race_weather_forecast_{year}_{event_slug}_*.json"
    elif year is not None:
        pattern = f"race_weather_forecast_{year}_*.json"
    elif event_slug:
        pattern = f"race_weather_forecast_*_{event_slug}_*.json"

    candidates = sorted(
        WEATHER_OUTPUT_DIR.glob(pattern),
        key=lambda path: path.stat().st_mtime,
        reverse=True,
    )

    if not candidates:
        return {
            "exists": False,
            "path": None,
            "age_hours": None,
            "age_formatted": None,
            "is_fresh": False,
            "should_regenerate": True,
            "refresh_interval_hours": WEATHER_REFRESH_HOURS,
            "reason": f"no files match pattern {pattern}",
        }

    latest = candidates[0]
    file_time = datetime.fromtimestamp(latest.stat().st_mtime, tz=timezone.utc)
    now = datetime.now(timezone.utc)
    age = now - file_time
    age_hours = age.total_seconds() / 3600
    is_fresh = age_hours < WEATHER_REFRESH_HOURS

    return {
        "exists": True,
        "path": str(latest),
        "file_time": file_time.isoformat(),
        "current_time": now.isoformat(),
        "age_hours": round(age_hours, 2),
        "age_formatted": _format_timedelta(age),
        "is_fresh": is_fresh,
        "should_regenerate": not is_fresh,
        "refresh_interval_hours": WEATHER_REFRESH_HOURS,
        "reason": "fresh file available" if is_fresh else "file older than refresh interval",
    }


def _format_timedelta(delta: timedelta) -> str:
    total_seconds = int(delta.total_seconds())
    if total_seconds < 60:
        return f"{total_seconds} seconds"
    minutes = total_seconds // 60
    if minutes < 60:
        return f"{minutes} minutes"
    hours = minutes // 60
    if hours < 24:
        return f"{hours} hours {minutes % 60} minutes"
    days = hours // 24
    return f"{days} days {hours % 24} hours"


def generate_race_weather_forecast(
    year: Optional[int] = None,
    *,
    event_name: Optional[str] = None,
    save_json: bool = True,
    force: bool = False,
    calendar_data: Optional[Dict[str, Any]] = None,
    http_get: Optional[HttpGetter] = None,
) -> RaceWeatherResult:
    """
    Build a weather forecast JSON payload for a specific race.
    """
    http_client: HttpGetter = http_get or requests.get
    target_year = year or datetime.now().year

    calendar_payload, calendar_path, calendar_freshness = _load_calendar_data(
        force_refresh=force, calendar_data=calendar_data
    )
    event = _select_target_event(calendar_payload, target_year, event_name)

    circuit_info = _resolve_circuit(event.get("event_name"), event.get("location"))
    event_label = event.get("event_name") or event.get("location") or "Unknown Event"
    event_slug = _slugify(event_label)

    existing = check_weather_forecast_freshness(target_year, event_label)
    if not force and existing.get("exists") and existing.get("is_fresh"):
        try:
            with open(existing["path"], "r", encoding="utf-8") as handle:
                cached = json.load(handle)
            metadata = cached.setdefault("metadata", {})
            metadata["is_fresh"] = True
            metadata["file_age_hours"] = existing.get("age_hours")
            metadata["last_freshness_check"] = datetime.now(timezone.utc).isoformat()
            cached["message"] = f"使用快取檔案（{existing.get('age_formatted')}）"
            return cached
        except Exception:
            print("[WARN] Failed to read cached weather JSON, regenerating...")

    race_local_str = event.get("race_date_local")
    race_dt_local = datetime.fromisoformat(race_local_str) if race_local_str else None
    if not race_dt_local:
        raise ValueError("Race date (local) missing in calendar data; cannot fetch weather.")

    race_day = race_dt_local.date()
    day_minus_one = race_day - timedelta(days=1)
    day_minus_two = race_day - timedelta(days=2)
    earliest_day = day_minus_two
    latest_day = race_day

    forecast_raw = _build_forecast_payload(
        lat=circuit_info["latitude"],
        lon=circuit_info["longitude"],
        timezone_id=circuit_info["timezone"],
        start_date=earliest_day,
        end_date=latest_day,
        http_get=http_client,
    )
    forecast_data = forecast_raw["raw"]
    forecast_daily = forecast_data.get("daily", {})
    forecast_hourly = forecast_data.get("hourly", {})
    daily_units = forecast_data.get("daily_units", {})

    forecast_days = [
        _build_daily_entry("race_minus_2", day_minus_two, forecast_daily, forecast_hourly, daily_units),
        _build_daily_entry("race_minus_1", day_minus_one, forecast_daily, forecast_hourly, daily_units),
        _build_daily_entry("race_day", race_day, forecast_daily, forecast_hourly, daily_units),
    ]

    historical_entries: Dict[str, Any] = {}
    historical_units: Dict[str, Any] = {}
    historical_years = [target_year - 1, target_year - 2]

    for history_year in historical_years:
        historical_day = race_day.replace(year=history_year)
        historical_minus_one = historical_day - timedelta(days=1)
        historical_minus_two = historical_day - timedelta(days=2)

        archive_raw = _build_archive_payload(
            lat=circuit_info["latitude"],
            lon=circuit_info["longitude"],
            timezone_id=circuit_info["timezone"],
            start_date=historical_minus_two,
            end_date=historical_day,
            http_get=http_client,
        )
        archive_data = archive_raw["raw"]
        archive_daily = archive_data.get("daily", {})
        archive_hourly = archive_data.get("hourly", {})
        archive_units = archive_data.get("daily_units", {})

        historical_units = archive_units or historical_units

        historical_entries[f"{history_year}_race_minus_2"] = _build_daily_entry(
            "race_minus_2", historical_minus_two, archive_daily, archive_hourly, archive_units
        )
        historical_entries[f"{history_year}_race_minus_1"] = _build_daily_entry(
            "race_minus_1", historical_minus_one, archive_daily, archive_hourly, archive_units
        )
        historical_entries[f"{history_year}_race_minus_0"] = _build_daily_entry(
            "race_day", historical_day, archive_daily, archive_hourly, archive_units
        )

    now_utc = datetime.now(timezone.utc)
    metadata: Dict[str, Any] = {
        "function_id": 96,
        "analysis_type": "race_weather_forecast",
        "generated_at": now_utc.isoformat(),
        "refresh_interval_hours": WEATHER_REFRESH_HOURS,
        "force_regenerated": force,
        "year": target_year,
        "event_name": event_label,
        "event_slug": event_slug,
        "round": event.get("round"),
        "location": event.get("location"),
        "country": event.get("country"),
        "race_date_local": event.get("race_date_local"),
        "race_date_utc": event.get("race_date_utc"),
        "calendar_reference_file": calendar_path,
        "calendar_freshness": calendar_freshness,
        "sources": {
            "calendar": "FastF1 (via season calendar function -f99)",
            "forecast": OPEN_METEO_FORECAST_URL,
            "historical": OPEN_METEO_ARCHIVE_URL,
        },
    }

    output_payload: RaceWeatherResult = {
        "success": True,
        "message": f"{target_year} {event_label} 天氣預報已生成",
        "metadata": metadata,
        "data": {
            "coordinates": circuit_info,
            "forecast": {
                "generated_at": now_utc.isoformat(),
                "days": forecast_days,
                "units": {
                    "daily": daily_units,
                    "hourly": forecast_data.get("hourly_units"),
                },
                "raw_source": forecast_raw["source"],
                "request_parameters": forecast_raw["requested_parameters"],
            },
            "historical": {
                "generated_at": now_utc.isoformat(),
                "entries": historical_entries,
                "units": {
                    "daily": historical_units,
                },
                "raw_source": OPEN_METEO_ARCHIVE_URL,
            },
            "calendar_event": event,
        },
    }

    if save_json:
        WEATHER_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
        
        # 🔧 FIX: 使用標準檔案命名格式，與其他分析一致
        # 標準格式: {analysis_type}_{year}_{race}_{session}.json
        # 例如: race_weather_forecast_2025_Singapore_R.json (不使用 slug 或時間戳)
        
        # 從完整賽事名稱提取國家名稱（例如 "Singapore Grand Prix" → "Singapore"）
        race_name = event_label.replace(" Grand Prix", "").replace(" Prix", "").strip()
        
        # 標準檔案名（不含時間戳，方便緩存系統找到）
        filename = f"race_weather_forecast_{target_year}_{race_name}_R.json"
        
        # 使用標準 JSON 輸出路徑（會自動處理子目錄）
        output_path = get_json_output_path("race_weather_forecast", filename)
        
        with open(output_path, "w", encoding="utf-8") as handle:
            json.dump(output_payload, handle, ensure_ascii=False, indent=2)
        metadata["output_file"] = str(output_path)
        print(f"\n[OK] Weather JSON saved to {output_path}")

    return output_payload


__all__ = [
    "generate_race_weather_forecast",
    "check_weather_forecast_freshness",
]

