import os
import shutil
import json
import re
from pathlib import Path

# Base configuration
AC_CONTENT_DIR = r"D:\SteamLibrary\steamapps\common\assettocorsa\content\cars"
BASE_CAR_MODEL = "rss_formula_hybrid_x_2026"
OUTPUT_DIR = os.path.join(os.getcwd(), "ac_sim_output")

# ... imports ...

# Team Performance Data (Initial Empty - Loaded from JSON)
TEAM_DATA = {}

class PhysicsCloner:
    def __init__(self, base_car_id=BASE_CAR_MODEL):
        self.base_car_id = base_car_id
        self.base_car_path = Path(AC_CONTENT_DIR) / base_car_id
        self.cloned_cars = []
        self._load_config()

    def _load_config(self):
        """Load physics parameters from external JSON"""
        global TEAM_DATA
        config_path = Path(os.getcwd()) / "physics_config.json"
        
        if config_path.exists():
            print(f"[INFO] Loading physics from {config_path}")
            with open(config_path, 'r') as f:
                TEAM_DATA = json.load(f)
        else:
            print("[WARN] physics_config.json not found! Using Fallback/Empty.")
            TEAM_DATA = {} # Fallback or keep hardcoded as backup? 
                           # Ideally we want to force usage of JSON now.



    def check_data_status(self):
        """Check if data folder exists"""
        data_path = self.base_car_path / 'data'
        if data_path.exists() and data_path.is_dir():
            print(f"[OK] 'data' folder found in {self.base_car_id}")
            return True
        else:
            print(f"[ERROR] 'data' folder NOT found. Unpack 'data.acd' in CM first!")
            return False

    def generate_grid(self):
        """Generate all cars based on TEAM_DATA"""
        if not self.check_data_status():
            return

        print(f"=== Starting Generation of {len(TEAM_DATA)*2} Cars ===")
        
        for team_name, data in TEAM_DATA.items():
            for driver in data['drivers']:
                self.clone_car(driver, team_name, data)

    def clone_car(self, driver_code, team_name, physics_data):
        """Clone and modify a single car"""
        # Create folder name: rss_fh_26_redbull_ver
        safe_team = team_name.replace(" ", "").lower()
        new_id = f"rss_fh_26_{safe_team}_{driver_code.lower()}"
        new_car_path = Path(AC_CONTENT_DIR) / new_id
        
        if new_car_path.exists():
            shutil.rmtree(new_car_path)
            
        print(f"-> Generating {new_id} ({team_name})...")
        
        # 1. Copy structure (excluding data.acd to save space if exists, but we need data folder)
        shutil.copytree(self.base_car_path, new_car_path, ignore=shutil.ignore_patterns('data.acd'))
        
        # 2. Modify UI
        self._update_json(new_car_path, driver_code, team_name)
        
        # 3. Modify Physics
        data_path = new_car_path / 'data'
        self._modify_aero(data_path, physics_data)
        self._modify_suspension(data_path, physics_data)
        self._modify_tyres(data_path, physics_data, new_id)
        
        # 4. Sound Fix (point to base sfx to save space/error)
        self._fix_sound(new_car_path)

        self.cloned_cars.append(new_id)

    def _update_json(self, car_path, driver, team):
        ui_file = car_path / 'ui' / 'ui_car.json'
        if not ui_file.exists(): return
        
        try:
            with open(ui_file, 'r', encoding='utf-8') as f:
                data = json.load(f)
        except:
             with open(ui_file, 'r', encoding='cp1252') as f: # Fallback encoding
                data = json.load(f)
            
        data['name'] = f"F1 2026 {team} #{driver}" # Display Name
        data['brand'] = team
        data['tags'].append(f"f1_2026_sim")
        data['description'] = f"Physics Clone for {driver} ({team})\nGenerated by F1T."
        
        with open(ui_file, 'w', encoding='utf-8') as f:
            json.dump(data, f, indent=4)

    def _modify_aero(self, data_path, physics):
        """Modify aero.ini CL_MULT and CD_MULT"""
        aero_file = data_path / 'aero.ini'
        if not aero_file.exists(): return
        
        with open(aero_file, 'r') as f:
            lines = f.readlines()
            
        new_lines = []
        for line in lines:
            # Look for [MAP_1] section multipliers
            # Simple regex replacement for safety
            if line.strip().startswith('CL_MULT'):
                # Line: CL_MULT = 5.185
                base_val = float(line.split('=')[1].split(';')[0].strip())
                new_val = base_val * physics['aero_downforce']
                new_lines.append(f"CL_MULT = {new_val:.4f} ; Modified by F1T\n")
            elif line.strip().startswith('CD_MULT'):
                base_val = float(line.split('=')[1].split(';')[0].strip())
                new_val = base_val * physics['aero_drag']
                new_lines.append(f"CD_MULT = {new_val:.4f} ; Modified by F1T\n")
            else:
                new_lines.append(line)
                
        with open(aero_file, 'w') as f:
            f.writelines(new_lines)

    def _modify_suspension(self, data_path, physics):
        """Modify suspensions.ini ARB FRONT"""
        susp_file = data_path / 'suspensions.ini'
        if not susp_file.exists(): return
        
        with open(susp_file, 'r') as f:
            lines = f.readlines()
            
        new_lines = []
        in_arb = False
        for line in lines:
            if line.strip() == '[ARB]':
                in_arb = True
                new_lines.append(line)
                continue
            elif line.strip().startswith('['):
                in_arb = False
                
            if in_arb and line.strip().startswith('FRONT'):
                # FRONT=120000
                base_val = float(line.split('=')[1].split(';')[0].strip())
                # Higher balance factor = Stiffer Front = More Understeer
                new_val = base_val * physics['susp_balance']
                new_lines.append(f"FRONT={int(new_val)}\n")
            else:
                new_lines.append(line)

        with open(susp_file, 'w') as f:
            f.writelines(new_lines)

    def _modify_tyres(self, data_path, physics, car_id):
        """Create custom tire LUTs for degradation"""
        tyres_file = data_path / 'tyres.ini'
        if not tyres_file.exists(): return
        
        # 1. Read tyres.ini to find LUT references
        with open(tyres_file, 'r') as f:
            content = f.read()
            
        # Find all WEAR_CURVE=...
        # We will create new LUTs and update the reference in ini
        
        def replace_lut(match):
            original_lut_name = match.group(1)
            original_lut_path = data_path / original_lut_name
            
            if not original_lut_path.exists():
                return match.group(0) # Skip if not found
                
            # Create new LUT
            new_lut_name = f"{original_lut_name.replace('.lut', '')}_{car_id}.lut"
            new_lut_path = data_path / new_lut_name
            
            self._create_degraded_lut(original_lut_path, new_lut_path, physics['tire_deg'])
            
            return f"WEAR_CURVE={new_lut_name}"

        new_content = re.sub(r'WEAR_CURVE=(.*\.lut)', replace_lut, content)
        
        with open(tyres_file, 'w') as f:
            f.write(new_content)

    def _create_degraded_lut(self, src_path, dst_path, deg_factor):
        """Read LUT, steepen the curve, save"""
        with open(src_path, 'r') as f:
            lines = f.readlines()
            
        new_lines = []
        for line in lines:
            if '|' in line:
                try:
                    parts = line.split('|')
                    x = parts[0]
                    y = float(parts[1])
                    
                    # Logic: 100% grip is baseline. 
                    # If y=98 (2% loss), new loss should be 2% * deg_factor
                    loss = 100.0 - y
                    new_loss = loss * deg_factor
                    new_y = 100.0 - new_loss
                    
                    new_lines.append(f"{x}|{new_y:.5f}\n")
                except:
                    new_lines.append(line)
            else:
                new_lines.append(line)
                
        with open(dst_path, 'w') as f:
            f.writelines(new_lines)

    def _fix_sound(self, new_car_path):
        """Point sfx to original car to avoid copying 100MB banks"""
        sfx_ini = new_car_path / 'sfx' / 'sfx.ini'
        # Usually easier to just copy the .bank file if it's not too huge, 
        # OR edit GUIDs.txt. 
        # AC often requires the bank filename to match key in GUIDs.
        # RSS uses a common bank usually.
        # Check source sfx folder
        src_sfx = self.base_car_path / 'sfx'
        dst_sfx = new_car_path / 'sfx'
        
        # If we didn't copy sfx (ignore), we need to copy it now? 
        # wait, shutil.copytree copied everything EXCEPT data.acd.
        # So sfx folder IS there.
        # But bank file references might rely on aliases.
        # Let's check if 'common.bank' exists or if it is 'rss_formula_hybrid_x_2026.bank'.
        pass

if __name__ == "__main__":
    cloner = PhysicsCloner()
    # cloner.clone_car("VER", "Red Bull Racing", TEAM_DATA["Red Bull Racing"]) # Test single
    cloner.generate_grid() # Generate All
